# Here we do a second k-means clustering on the postures identified with first kmeans with cluster_skeletons.R (across annotations/datasets).

# Needed: "...cluster_centers_reduced.RDS" &
#         "..._angle_data_postures_per_dataset.RDS"

#as computed by the "cluster_skeletons.R" and "plot_postures.R" scripts

#Also needed: A metadata file that is located in the folder that contains the "raw_data.RDS" files generated by the "data_grouping.R" (i.e. the directory that contains the acquired experiments)
# This file should be named "toprocess_cluster_skeletons_2.txt" and contain the conditions you want to cluster,

# To run the script type: Rscript cluster_skeletons_2.R "the location of your raw data folder"
# e.g. Rscript cluster_skeletons.R /media/fpreuss/raid5/timelapses/analysis/paper/data/raw


options(warn=-1)

library(tidyverse)
options(dplyr.summarise.inform=FALSE)


###### functions ######


#Load data for clustering of posture libraries across annotations
#function to load posture library
#ID to unify posture IDs across annotations
load_cc_cluster_centers_reduced <- function(x){
  readRDS(x) %>%
    mutate(annotation=gsub("^(.+)_cluster_centers_reduced.RDS", "\\1",basename(x))) %>%
    mutate(ID = paste0(newID, "_", annotation))
}

#function to load posture library
#ID to unify posture IDs across annotations
load_cc_perc_norm_angle_data_postures_per_dataset <- function(x){
  readRDS(x) %>%
    mutate(annotation = gsub("^(..+)_perc_norm_angle_data_postures_per_dataset.RDS","\\1",basename(x)))
}



# function to compute total within-cluster sum of square
wss <- function(k) {
  k <- kmeans(ccr_for_clustering, k)
  perc <- k$betweenss / k$totss
  return(perc)
}

#########################

#define base path
raw_path <- commandArgs(trailingOnly = TRUE)[1]
base_path <- file.path(dirname(raw_path), "skeletonized","clustered")

save_path <-  file.path(dirname(raw_path), "skeletonized","clustered_2")
dir.create(save_path,recursive = TRUE)
#catch timelapses_metadata.txt location
toprocess_file_path <- file.path(raw_path, "toprocess_cluster_skeletons_2.txt")

#extract list of datasets to process from "timelapses_metadata.txt" file
datasets <- as.matrix(read.table(toprocess_file_path))

#select datasets to re-cluster together based on "timelapses_metadata.txt" file
cc_list <- grep(paste(paste0(datasets,"_cluster_centers_reduced.RDS"),collapse="|"),list.files(base_path, pattern=".+_cluster_centers_reduced.RDS", full.names = TRUE),value = TRUE)

#load data
cluster_centers_reduced <- cc_list %>%
  map_df(., load_cc_cluster_centers_reduced)


cat(paste0("\n\nProcessing and plotting the following datasets: ", paste(unique(cluster_centers_reduced$annotation),collapse="\n"),"\n\n"))


#new data frame, every column is an x or y position for each segment of the posture (newID)
# newID is the ID two mirrored postures share after kmeans
# only new_ID == 1 to show only one of the two mirrored
ccr_for_clustering <- filter(cluster_centers_reduced,newID_sub == 1) %>%
  select(ID,index,X,Y) %>%
  pivot_wider(names_from = index, values_from = c(X,Y)) %>%
  # mutate(newID = paste0("posture_", newID)) %>%
  column_to_rownames(var = "ID")



#elbow plot for second round of kmeans

# Compute and plot wss for k = 1 to k = 15
k_values <- 1:15

# extract wss for 2-15 clusters
wss_values <- data.frame(expvar = map_dbl(k_values, wss)) %>%
  mutate(k=k_values)

#do the plot
ggplot(data=wss_values,aes(x=k, y=expvar))+
  geom_point()+
  geom_line()+
  scale_x_continuous(breaks = seq(min(k_values), max(k_values)))+
  theme_classic()

ggsave(file.path(save_path,paste0("second_clustering_elbow_plot",".png")))

# second round of kmeans
#perform the clustering
#this is done by another round of kmeans clustering this time only on posture libraries but across annotations/datasets
#define the number of k for kmeans
how_many_clusters <- 3

#kmeans clustering is performed here
k_ccr <- kmeans(ccr_for_clustering, how_many_clusters)

#new dataframe that contains the ID (posture ID (newID) combined with annotatation) and the new posture group the new ID belongs to (after clustering)
postures_grouped <- data.frame(posture_grouped= as.character(k_ccr$cluster), ID = rownames(ccr_for_clustering),stringsAsFactors = FALSE)

#bring together original posture library with new posture group
cluster_centers_reduced_grouped <- left_join(cluster_centers_reduced, postures_grouped, by="ID") %>%
  filter(newID_sub == 1) %>%
  mutate(posture_grouped = paste0("group_",posture_grouped)) %>%
  select(annotation,newID,index,X,Y,angle, posture_grouped)


#Load data for quantifying posture group occurences (this is the angle_data_postures_per_dataset from "plot_postures.Rmd")
#we also need this to get ID2 (which is the names of postures in the heatmap)

#all posture libraries (aka "cluster centers reduced") have to be in one folder
cc_list <- list.files(base_path,"_angle_data_postures_per_dataset.RDS", full.names = TRUE,recursive=TRUE)

#load data and append new postures_grouped ID
angle_data_postures_per_dataset <- cc_list %>%
  map_df(., load_cc_perc_norm_angle_data_postures_per_dataset) %>%
  mutate(ID = paste0(newID, "_", gsub(" ","_",annotation))) %>%
  left_join(postures_grouped, by="ID") %>%
  select(-ID) %>%
  mutate(number_k = how_many_clusters)


#save the results of second kmeans together with relative occurences (as in angle_data_postures_per_dataset)
saveRDS(angle_data_postures_per_dataset, file.path(save_path, paste0("second_kmeans_with_k_",how_many_clusters, "_occurences.RDS")))
#save the results of second kmeans with posture angles etc
saveRDS(cluster_centers_reduced_grouped, file.path(save_path, paste0("second_kmeans_with_k_",how_many_clusters, "_angles.RDS")))




