```{r message=FALSE, include=FALSE}


base_path <- "/media/fpreuss/raid5/timelapses/analysis/200703/"
target_path <- file.path(base_path, "data","posture","skeletonized_filtered")

```

```{r include=FALSE}

files_to_process <- list.files(target_path,"skeletonized_filtered.rds", full.names = TRUE, ignore.case = TRUE)

#define which .rds files to include
files_titles <-  c("1:10_OP50_ske")
files_to_process <- grep(paste0(files_titles,collapse="|"),files_to_process,value = TRUE)

#what is the conversion factor ? how many µm equals one pixel
conversion_factor <- 6.25
#only tracks longer than 15 sec (if 2fps)
minimal_track_length <- 30
downsampled_to <- 2


#function to load posture library
#ID to unify posture IDs across annotations
load_skeletonized_filtered_subset <- function(x){
  readRDS(x) %>%
    #estimate 15 minutes as lag before experiment
    mutate(minutes = 15 + ((tp-1)*8+(tp-1)*0)) %>%
    #round to half hour steps
    # mutate(hours_rounded = ceiling(minutes/60*2)/2) %>%
    #round to full hours steps
    mutate(hours_rounded = ceiling(minutes/60)) %>%
    filter(hours_rounded <= 12) %>%
    #summarise by frame and keep location
    mutate(ID = paste0(dataset_ID,"_", tp,"_",TrackID)) %>%
    group_by(ID,hours_rounded,frame,location_x,location_y) %>%
    nest() %>%
    group_by(ID) %>%
    #calculate velocity, angular velocity and center the track position
    mutate(x_lag=lag(location_x,n=1) - location_x, y_lag = lag(location_y, n=1) - location_y) %>%
    mutate(x_lead=lead(location_x, n=1) - location_x, y_lead=lead(location_y, n=1) - location_y) %>%
    # calculate the angle and convert to degrees
    mutate(angle_track = suppressWarnings(180 - (as.numeric(mapply(angle,x_lag,y_lag,x_lead,y_lead)))*180/pi)) %>%
    # measure distance between current point and 1 second before
    mutate(local_distance=suppressWarnings(as.numeric(mapply(distance,lag(location_x,n=2),lag(location_y,n=2),location_x,location_y)))) %>%
    #this will result in velocity based on local distance (mm/s)
    mutate(velocity = local_distance*conversion_factor/2/1000) %>%
    filter(velocity > 0.01) %>%
    filter(angle_track < 50) %>%
    # now calculate for the whole track (== ID)
    group_by(ID,hours_rounded) %>%
    #the track should not have any missing frames
    mutate(length_track = n(), length_track2=last(frame)-first(frame)+1) %>%
    filter(length_track == length_track2) %>%
    #filter out tracks that are too short
    filter(length_track > minimal_track_length) %>%
    select(-c(length_track2)) %>%
    # nest() %>%
    # group_by(hours_rounded) %>%
    # sample_n(25) %>%
    # unnest(cols=c(data)) %>%
    unnest(cols=c(data)) %>%
    ungroup()
    
}


#load data
skeletonized_filtered_subset <- files_to_process %>%
  map_df(., load_skeletonized_filtered_subset)

```

```{r include=FALSE}
save_path <- file.path(base_path,"plots","posture","head_angles")
dir.create(save_path)

plot_posture_examples <- function(data_to_plot,X,Y){
  ggplot(data_to_plot, aes_string(x=X,y=Y,color="angle"))+
    geom_point(data=filter(data_to_plot,is_head == "YES"), aes_string("X","Y"),color="orange",size=8,shape=16,alpha=0.5) +
    geom_point(size=5) +
    theme_void()+
    coord_fixed(ratio = 1)+
    scale_color_gradient2(low = "deepskyblue", mid = "lavender",
                          high = "deeppink",midpoint=0,limits=c(-1.5,1.5),na.value="grey") +
    theme(plot.title = element_text(face = "bold"))
  
}

test_track <- skeletonized_filtered_subset %>%
  filter(ID == "2020-06-25_17-58-07_11_track_72" |
        ID == "2020-06-22_17-58-37_84_track_13" |
        ID == "2020-06-25_17-58-07_65_track_63" |
        ID == "2020-06-23_17-58-40_8_track_26"  )


# for(i in unique(test_track$frame)){
#   test_track_selected_frame <- test_track %>%
#     filter(frame == i)
#   plot_posture_examples(test_track_selected_frame, "X", "Y")+
#     ggsave(file.path(save_path,paste0(i,"_example_track.png")),height=5,width=5)
# }
```

```{r include=FALSE}
#show segment angle diagrams (aka "wave diagrams") next to skeleton of the same worm

#function to plot the wave diagram
plot_wave <- function(dataset){
  
  data_to_plot <- dataset %>%
    group_by(ID) %>%
    filter(!index %in% c(1,2,25,26)) %>%
    mutate(min_frame = min(frame)) %>%
    mutate(seconds = (frame - min_frame)/downsampled_to)
    

  # Track_ID <- unique(data_to_plot$TrackID)
  # hours_rounded <- unique(data_to_plot$hours_rounded)

  ggplot(data_to_plot, aes(x=seconds,y=index,fill=angle))+
    geom_tile()+
    scale_x_continuous(limits=c(0,max(data_to_plot$seconds)))+
    scale_y_continuous(trans="reverse")+
    scale_fill_gradient2(low = "cornflowerblue",mid ="white",high = "brown2",midpoint=0,na.value="white") +
    theme_classic()+
    theme(
          legend.position = "top")+
    labs(x="seconds")+
    theme(strip.text.x = element_text(size = 10))+
    labs(fill = "Intersegment angle (rad)") +
    facet_wrap(vars(ID))+
    coord_equal()
}

plot_wave(test_track)


# for (f in min_frame:max_frame){
#   data_plot <- test_track %>%
#       filter(frame == f)
#    
#     p1<-plot_skeleton(data_plot)
#     #print(p1)
#     p2 <- plot_wave(test_track)
#     #print(p2)
#     plot_grid(p2,p1,align=("v"),scale=c(1,0.8))+ theme(plot.background = element_rect(fill = "black"))
#     ggsave(paste0(file.path(base_location,"ggplots"),"/","Wave_and_skeleton_","timepoint_",timepoint,"_",track,"_","frame_",f,".png"))
# }
```
