#set parameters here
```{r, include=FALSE}

#Set the location folder of the raw data (of all experiments you want to plot)
base_path <- "/media/fpreuss/raid5/timelapses/analysis/200703/"

```

#load files
```{r, include=FALSE}

target_path <- file.path(base_path,"data", "other_raw")

#list of .rds files in data folder
files_to_process <- list.files(target_path, "raw_data.rds", full.names = TRUE, ignore.case = TRUE)

#select dataset
files_to_process <- grep(".+long.+", files_to_process,value=TRUE)

#pixel to µm conversion
#this is with magnifaction 3.2
conversion_factor <- 6.25


imported_data <- NULL
#load all .rds files and append to one data frame ('imported_data')
for (file in files_to_process){
  imported_data_temp <- readRDS(file) %>%
    #calculate average size, major and minor axis BY TRACK
    group_by(annotation,dataset_ID, tp,minutes,TrackID) %>%
    #only tracks that are longer than 10s
    #same as for calculating motion parameters
    summarise(Duration_of_track_in_min = Duration_of_track/2/60) %>%
    mutate(hours_rounded = ceiling(minutes/60)) %>%
    filter(hours_rounded <= 20) %>%
    group_by(tp) %>%
    mutate(number_of_tracks = n())
    
  imported_data <- rbind(imported_data, imported_data_temp)  
}

```

#create plotting functions
```{r, include=FALSE}
save_path <- file.path(base_path,"plots","tracking_parameters")
dir.create(save_path)

se <- function(x) sqrt(var(x)/length(x))

imported_data %>%
  mutate(annotation = "both") %>%
  group_by(hours_rounded) %>%
  summarise(mean_duration_in_min= mean(Duration_of_track_in_min), maxsd=mean(Duration_of_track_in_min)+sd(Duration_of_track_in_min),minsd=mean(Duration_of_track_in_min)-sd(Duration_of_track_in_min)) %>%
  mutate(minsd  = ifelse(minsd < 0, 0, minsd)) %>%
  ggplot(.,aes(y = mean_duration_in_min, x = hours_rounded,group=annotation)) +
    geom_ribbon(aes(ymin=minsd, ymax=maxsd,group=annotation),fill="lightgray", color="lightgray")+
    geom_line(size=1.2)+
    geom_point(size=3,color="black")+
    theme_classic()+
    scale_y_continuous(limits=c(0,NA))+
    labs(y="Track duration (min)",x="time (hours)")+
    theme(strip.background = element_rect(colour = "white", fill = "white"),
      strip.text.x = element_text(size=20,colour = "black", face = "bold"),
      axis.text.x = element_text(size=15, face="bold"),
      axis.title.x = element_text(size=20, face="bold"),
      axis.text.y = element_text(size=15, face="bold"),
      axis.title.y = element_text(size=20, face="bold"),
      axis.line = element_line(colour = 'black', size = 1.2),
      axis.ticks = element_line(colour = "black", size = 1.2))+
    ggsave(file.path(save_path,paste0("track_length",".png")),height=7,width=7)



```

