#set parameters here
```{r, include=FALSE}

library(tidyverse)
library(viridis)
library(wesanderson)
#for statistic testing
library(rstatix)

#Set the location folder of the raw data (of all experiments you want to plot)
base_path <- "/Users/fpreuss/Desktop/paper/data"

target_path <- file.path(base_path, "size")
save_path <- file.path(dirname(base_path),"plots","sizes")
dir.create(save_path)

```

#load files
```{r, include=FALSE}

#list of .rds files in data folder
files_to_process <- list.files(target_path, "converted", full.names = TRUE, ignore.case = TRUE)

#pixel to µm conversion
#this is with magnifaction 3.2
conversion_factor <- 6.25

imported_data <- NULL
#load all .rds files and append to one data frame ('imported_data')
for (file in files_to_process){
  imported_data_temp <- readRDS(file) %>%
    #make annotation unique for dataset
    mutate(annotation = basename(file)) %>%
    mutate(annotation = gsub("(^.+)\\_size.+", "\\1", annotation))
  
  imported_data <- rbind(imported_data, imported_data_temp)
}
imported_data_temp <- NULL
unique(imported_data$annotation) 

```


#create plotting functions
```{r, include=FALSE}
library("ggridges")

se <- function(x) sqrt(var(x)/length(x))

data_summary <- function(x) {
   m <- mean(x)
   ymin <- m-sd(x)
   ymax <- m+sd(x)
   return(c(y=m,ymin=ymin,ymax=ymax))
}


#function to plot distributions
plot_distribution_ridges <- function(data_to_plot, X, Y){ 
  ggplot(data_to_plot,aes_string(x = X ,y =Y)) +
    geom_density_ridges_gradient(aes(fill=stat(x)),scale = 1) +
    scale_fill_viridis(option="plasma",limits=c(200,500)) +
    scale_x_continuous(limits=c(0,750))+
    theme_classic()+
    labs(x="length (µm)",y="time (hours)")+
    theme(strip.background = element_rect(colour = "white", fill = "white"),
      strip.text.x = element_text(size=15,colour = "black", face = "bold"),
      axis.text.x = element_text(size=10, face="bold"),
      axis.title.x = element_text(size=15, face="bold"),
      axis.text.y = element_text(size=10, face="bold"),
      axis.title.y = element_text(size=15, face="bold"),
      axis.line = element_line(colour = 'black', size = 1),
      axis.ticks = element_line(colour = "black", size = 1))
}


parameters <- c("midline")

plots_sizes <- function(selected_annotations, selected_timepoints,parameter,plot_width, plot_height){
  
  save_path_temp_parameter <- file.path(save_path,"comparisons",parameter)
  dir.create(save_path_temp_parameter,recursive=TRUE)
  
  save_path_temp_plottype <- file.path(save_path,"boxplots")
  dir.create(save_path_temp_plottype,recursive = TRUE)
  
  #boxplots
  data_to_plot <- imported_data %>%
    filter(annotation %in%  selected_annotations) %>%
    filter(hours_rounded %in% selected_timepoints) %>%
    mutate(hours_rounded = as.factor(hours_rounded)) %>%
    arrange(match(annotation, selected_annotations)) %>%
    mutate(annotation=factor(annotation, levels=selected_annotations))
  
  extract_numbers <- data_to_plot %>%
    group_by(annotation, dataset_ID,hours_rounded) %>%
    mutate(number_of_tracks_per_hour=n()) %>%
    mutate(annotation = paste0(hours_rounded, "-",annotation, " #tracks/hour: ",number_of_tracks_per_hour)) %>%
    ungroup() %>%
    wilcox_test(midline ~ hours_rounded,detailed = TRUE) %>%
    add_significance()
  
  write.table(extract_numbers, file.path(save_path_temp_parameter,paste0("stats_",paste(selected_annotations, collapse="_"),"_",min(selected_timepoints),"-",max(selected_timepoints), ".txt")))
              
  ggplot(data_to_plot,aes_string(x ="hours_rounded" ,y =parameter,fill="annotation")) +
    geom_point(size=0.75,alpha=0.25,shape=21,position=position_jitterdodge(0.25))+
    geom_boxplot(outlier.shape = NA,alpha=0.5)+
    theme_classic()+
    # expand_limits(y=0)+
    labs(x="time (hours)")+
    theme(strip.background = element_rect(colour = "white", fill = "white"),
      strip.text.x = element_text(size=15,colour = "black", face = "bold"),
      axis.text.x = element_text(size=10, face="bold"),
      axis.title.x = element_text(size=15, face="bold"),
      axis.text.y = element_text(size=10, face="bold"),
      axis.title.y = element_text(size=15, face="bold"),
      axis.line = element_line(colour = 'black', size = 1),
      axis.ticks = element_line(colour = "black", size = 1))+
    scale_fill_manual(values = pal)+
    scale_color_manual(values = pal)+
    # facet_wrap(vars(annotation))+
    ggtitle(paste0(parameter, "_boxplots_",paste(selected_annotations, collapse="_")))
  
    ggsave(file.path(save_path_temp_plottype,paste0(parameter, "_boxplots_",paste(selected_annotations, collapse="_"),"_",min(selected_timepoints),"-",max(selected_timepoints), ".png")),height=plot_height,width=plot_width)
  


  #mean with standard error
  save_path_temp_plottype <- file.path(save_path_temp_parameter,"mean_se")
  dir.create(save_path_temp_plottype)
  data_to_plot %>%
    group_by(hours_rounded,annotation) %>%
    #here we calculate the standard error instead of standard derivation
    summarise(mean_param= mean(eval(as.name(parameter))), maxse=mean(eval(as.name(parameter)))+se(eval(as.name(parameter))),minse=mean(eval(as.name(parameter)))-se(eval(as.name(parameter)))) %>%
    mutate(hours_rounded=factor(hours_rounded, levels=unique(hours_rounded))) %>%
    ggplot(.,aes_string(x = "hours_rounded" ,y ="mean_param",color="annotation",fill="annotation",group="annotation")) +
      geom_ribbon(aes(ymin=minse, ymax=maxse,group=annotation),fill="lightgray", color="lightgray", alpha=.5)+
      geom_line(size=1.2)+
      geom_point(aes(color=annotation),shape=21, size=3,color="black")+
      theme_classic()+
      expand_limits(y=0)+
      labs(x="time (hours)",y="Size (µm)")+
      theme(strip.background = element_rect(colour = "white", fill = "white"),
        strip.text.x = element_text(size=15,colour = "black", face = "bold"),
        axis.text.x = element_text(size=10, face="bold"),
        axis.title.x = element_text(size=15, face="bold"),
        axis.text.y = element_text(size=10, face="bold"),
        axis.title.y = element_text(size=15, face="bold"),
        axis.line = element_line(colour = 'black', size = 1),
        axis.ticks = element_line(colour = "black", size = 1))+
      scale_fill_manual(values = pal)+
      scale_color_manual(values = pal)+
      ggtitle(paste0(parameter, "_meanse_",paste(selected_annotations, collapse="_")))
  
      ggsave(file.path(save_path_temp_plottype,paste0(parameter, "_meanse_",paste(selected_annotations, collapse="_"),"_",min(selected_timepoints),"-",max(selected_timepoints), ".png")),height=plot_height,width=plot_width)
  
  #mean with standard error
  save_path_temp_plottype <- file.path(save_path_temp_parameter,"mean_sd")
  dir.create(save_path_temp_plottype)
  
  data_to_plot %>%
    group_by(hours_rounded,annotation) %>%
    #here we calculate the standard error instead of standard derivation
    summarise(mean_param= mean(eval(as.name(parameter))), maxsd=mean(eval(as.name(parameter)))+sd(eval(as.name(parameter))),minsd=mean(eval(as.name(parameter)))-sd(eval(as.name(parameter)))) %>%
    mutate(hours_rounded=factor(hours_rounded, levels=unique(hours_rounded))) %>%
    ggplot(.,aes_string(x = "hours_rounded" ,y ="mean_param",color="annotation",fill="annotation",group="annotation")) +
      geom_ribbon(aes(ymin=minsd, ymax=maxsd,group=annotation),fill="lightgray", color="lightgray", alpha=.5)+
      geom_line(size=1.2)+
      geom_point(aes(color=annotation),shape=21, size=3,color="black")+
      theme_classic()+
      expand_limits(y=0)+
      labs(x="time (hours)",y="Size (µm)")+
      theme(strip.background = element_rect(colour = "white", fill = "white"),
        strip.text.x = element_text(size=20,colour = "black", face = "bold"),
        axis.text.x = element_text(size=15, face="bold"),
        axis.title.x = element_text(size=20, face="bold"),
        axis.text.y = element_text(size=15, face="bold"),
        axis.title.y = element_text(size=20, face="bold"),
        axis.line = element_line(colour = 'black', size = 1),
        axis.ticks = element_line(colour = "black", size = 1))+
      scale_fill_manual(values = pal)+
      scale_color_manual(values = pal)+
      ggtitle(paste0(parameter, "_meansd_",paste(selected_annotations, collapse="_")))
  
      ggsave(file.path(save_path_temp_plottype,paste0(parameter, "_meansd_",paste(selected_annotations, collapse="_"),"_",min(selected_timepoints),"-",max(selected_timepoints), ".png")),height=plot_height,width=plot_width)
  
}

```


# OP50 vs Agar 
```{r, include=FALSE}
selected_annotations <- c("Agar_long_1","OP50_long_2")
selected_timepoints <- unique(imported_data$hours_rounded)


for (parameter in parameters){
  pal <- wes_palette("Darjeeling1")[c(1,5)]
  plots_sizes(selected_annotations, selected_timepoints, parameter,10,7)
}

selected_annotations <- c("OP50_long_2")
selected_timepoints <- c(1,12,18)
for (parameter in parameters){
  pal <- wes_palette("Darjeeling1")[c(5)]
  plots_sizes(selected_annotations, selected_timepoints, parameter,5,3)
}

```
