##set parameters here
```{r, include=FALSE}
base_path <- "/media/fpreuss/raid5/timelapses/analysis/200703/"
```

#we look into the "data" folder for "raw_data" files but only processes those that are not already in the processed "motion"folder
```{r, include=FALSE}

target_path <- file.path(base_path, "data")
save_path <- file.path(target_path, "motion")
dir.create(save_path)

#pixel to µm conversion
#this is with magnifaction 3.2
conversion_factor <- 6.25

#set parameters
#We record at 2fps
offset =2 #== 1 seconds
max_gaps = 0 
duration = 20 #==10 seconds
binning_factor = 20 #==10 seconds

#list of .rds files in data folder that were already analysed for centroid tracking
annotations_already_processed <- unique(gsub(".+\\/(.+)\\_centroid.+","\\1",list.files(save_path, "centroid_tracking", full.names = TRUE, ignore.case = TRUE)))
annotations_to_be_processed <- gsub("(.+)\\_raw_data.+","\\1",list.files(target_path,"raw_data", ignore.case = TRUE))
#remaining annotations to process
files_to_process_cleaned <- annotations_to_be_processed[!annotations_to_be_processed %in% annotations_already_processed]
#get file path
if (length(files_to_process_cleaned) > 0){
  files_to_process <- list.files(target_path, pattern=paste0(paste0("^",files_to_process_cleaned,"_raw_data"),collapse="|"), full.names = TRUE, ignore.case = TRUE)
  number_files_to_process <- length(files_to_process_cleaned)
  cat("The following files will be processed:\n", paste(files_to_process, collapse = "\n"))
  #for each of these files calculate the centroid tracking statistics
  for (file in files_to_process){
    cat("\n\nNow processing: ", file)
    imported_data <- readRDS(file)
    annotation <- unique(imported_data$annotation)
    annotation_underscored <- gsub(" ", "_", annotation)
    
    
    #calculate centroid tracking statistics per bin
    centroids_tracking_bins <- centroids_summarise_per_bin(imported_data,conversion_factor,offset,binning_factor,max_gaps,duration)
    created_file_path <- file.path(save_path,paste0(annotation_underscored,"_centroid_tracking_bins.RDS"))
    number_files_to_process <<- number_files_to_process - 1
    saveRDS(centroids_tracking_bins, file=created_file_path)
    cat(paste0("\n\nCentroids tracked, averaged over bins. \nDataset ", file, " was processed\nand saved under ", created_file_path, "\n", number_files_to_process, " datasets waiting to be processed.\n\n"))
 
    
    rm(imported_data)
    gc()
  }
}else{
  cat("All datasets in ", target_path," already processed.")
}

```

