

```{r, include=FALSE}

#define data paths
base_path <- "/media/fpreuss/raid5/timelapses"

```

```{r, include=FALSE}

save_path <- file.path(base_path,"analysis", "200703","data")
dir.create(save_path)



list_of_datasets <- matrix(c(
  # "2020-06-22_17-58-37", "OP50",
  # "2020-06-23_17-58-40", "OP50",
  # "2020-06-25_17-58-07", "OP50",
  # "2020-11-18_18-54-57", "OP50 with Az NGM",
  # "2020-11-20_18-41-05", "OP50 with Az NGM",
  # "2020-11-23_17-13-46","OP50 with Az NGM"
  # "2019-03-25_18-10-06", "NGM",
  # "2019-11-18_18-43-57", "NGM",
  # "2019-11-20_17-29-55", "NGM",
  # "2020-05-25_18-48-32", "NGM RT",
  # "2020-05-26_18-19-46", "NGM RT",
  # "2020-05-27_20-33-10", "NGM RT",
  # "2020-06-04_19-04-35", "Agar",
  # "2020-06-08_17-57-26", "Agar",
  # "2020-12-03_13-21-25", "Agar"
  # "2020-07-16_18-36-46","Agar with NAD",
  # "2020-07-17_12-47-20", "Agar with NAD",
  # "2020-07-24_19-06-57", "Agar with NAD",
  # "2020-07-27_16-34-21", "Agar with NAD",
  # "2020-08-27_12-06-16", "MT14984 OP50",
  # "2020-09-02_18-49-24", "MT14984 OP50",
  # "2020-09-09_18-42-17","MT14984 OP50",
  # "2019-04-23_17-46-08", "daf2",
  # "2019-05-07_12-15-40", "daf2",
  # "2020-02-20_18-53-49", "OP50 after 6h exit",
  # "2020-02-21_15-58-43", "OP50 after 6h exit",
  # "2020-03-03_19-35-55", "OP50 after 6h exit",
  # "2020-02-26_18-31-08", "NGM after 6h exit",
  # "2020-02-27_17-51-43", "NGM after 6h exit",
  # "2020-02-28_17-38-15", "NGM after 6h exit",
  # "2020-11-11_11-14-36", "OP50_long_1"
  # "2020-11-02_14-47-38", "OP50_long_2"
  # "2020-11-03_17-51-40", "Agar_long_1"
  # "2020-12-04_12-19-53", "Agar_long_2"
  # "2021-03-29_17-50-33", "KQ1366 OP50",
  # "2021-03-30_17-52-54","KQ1366 OP50",
  # "2021-04-14_17-37-14", "KQ1366 OP50"
  # "2021-03-30_17-52-54","KQ1366 OP50_long_1"
  "2021-04-14_17-37-14", "KQ1366 OP50_long_2"
  # "2021-03-25_13-19-30","BAT2206",
  # "2021-03-25_13-19-30","BAT2206 OP50_long_1"
  # "2021-04-03_17-56-49","BAT2206",
  ),byrow = TRUE,ncol=2)

colnames(list_of_datasets) <- c("dataset_ID", "annotation")

nested_list_of_datasets <- list_of_datasets %>%
  as.data.frame(.) %>%
  nest(data=c(dataset_ID))


for (row in 1:nrow(nested_list_of_datasets)){
  target_folder_general <-as.character(pull(unnest(nested_list_of_datasets[row,2],cols=c(data))))
  annotation <- as.character(pull(nested_list_of_datasets[row,1]))
  target_folder_analysis <- file.path(base_path, target_folder_general, "analysis")
  
  #load metadata (for all datasets)
  metadata_file <- list.files(file.path(base_path,target_folder_general),pattern=".+\\_metadata.txt$", full.names = TRUE)
  metadata <- data.frame(sapply(metadata_file, function (x) read.delim(x,header=FALSE,check.names = FALSE)))
  colnames(metadata) <- metadata_file
  colnames(metadata) <- as.character(gsub(".+\\/", "",colnames(metadata)))
  colnames(metadata) <- as.character(gsub("_metadata.txt", "",colnames(metadata)))
  time_elapsed <- apply(metadata,2, function(x) as.numeric(gsub(".+\\s([0-9]+).*", "\\1",x[grepl("Time elapsed.+\\:\\s(.+)",x)])))
  time_elapsed <- as.data.frame(time_elapsed)
  time_elapsed$dataset <- colnames(metadata)
  
  
  #timepoint length, in minutes
  #attention to divide everything by 60, because this value is entered in seconds
  timepoint_length <- apply(metadata,2, function(x) as.numeric(gsub(".+\\:\\s(.+)", "\\1",x[grepl("Timepoint length\\:\\s(.+)\\.",x)])))/60
  timepoint_length <- as.data.frame(timepoint_length)
  timepoint_length$dataset <- colnames(metadata)
  
  
  #timestep, in minutes
  timestep_length <- apply(metadata,2, function(x) as.numeric(gsub(".+every(.+)minutes\\.", "\\1",x[grepl(".+every(.+)minutes\\.",x)])))
  timestep_length <- as.data.frame(timestep_length)
  timestep_length$dataset <- colnames(metadata)
  
  #plate type
  plate_type <- apply(metadata,2, function(x) gsub(".+\\,(.+)\\,.+", "\\1",x[grepl("Timelapse plate type\\:",x)]))
  plate_type <- as.data.frame(plate_type)
  plate_type$dataset <- colnames(metadata)
  
  #worm type
  worm_type <- apply(metadata,2, function(x) gsub(".+\\:\\s(.+)", "\\1",x[grepl("Used line\\:",x)]))
  worm_type <- as.data.frame(worm_type)
  worm_type$dataset <- colnames(metadata)


  #list zip files in target_folder_analysis
  find_zip_files <- function(target_folder_analysis){
    files <- sort(as.numeric(gsub("(\\d+)\\..+","\\1",list.files(target_folder_analysis,pattern=".zip"))))
    file.path(target_folder_analysis,paste0(files, ".csv.zip"))
  }
  
  
  imported_data <-  unlist(map(target_folder_analysis,find_zip_files)) %>%
    map_df(.,function(x) read_csv(x, col_types=cols(),col_names=TRUE) %>%
    mutate(file_name=x)) %>%
    mutate(dataset_ID = gsub(".+\\/([0-9]+\\-[0-9]+\\-[0-9]+\\_[0-9]+\\-[0-9]+\\-[0-9]+)\\/.+", "\\1",file_name)) %>%
    #replace all whitespaces in column names with "_"
    rename_all(list(~gsub("\\s", "_",.))) %>%
    inner_join(., time_elapsed,by = c("dataset_ID" = "dataset")) %>%
    inner_join(., timepoint_length,by = c("dataset_ID" = "dataset")) %>%
    inner_join(., timestep_length,by = c("dataset_ID" = "dataset")) %>%
    inner_join(., plate_type, by = c("dataset_ID" = "dataset")) %>%
    inner_join(., worm_type, by = c("dataset_ID" = "dataset")) %>%
    mutate(timestep_length = ifelse(timepoint_length > timestep_length, 0,timestep_length-timepoint_length)) %>%
    mutate(minutes = time_elapsed + ((tp-1)*timepoint_length+(tp-1)*timestep_length)) %>%
    na.omit() %>%
    mutate(annotation = annotation) %>%
    select(c(TrackID, Number_of_gaps, Mean_velocity, Maximal_velocity, Minimal_velocity, Median_velocity,
             Velocity_standard_deviation, Duration_of_track, Track_start, Track_stop, Track_displacement,
             location_x, location_y, Size, Circularity, Convexity, Eccentricity, Main, Minimum, Maximum,
             Major, Minor, Boundary, Boxivity, Roundness, Solidity, Prediction, Prediction_confidence,
             frame, recorded_fps, downsampled_to, bitmask, bitmask_dim_X, bitmask_dim_Y, tp, file_name,
             dataset_ID, time_elapsed, timepoint_length, timestep_length, plate_type, worm_type,
             minutes, annotation))
  

    annotation_underscored <- gsub(" ", "_", annotation)
    created_file_path <- file.path(save_path,paste0(annotation_underscored, "_raw_data.rds"))
    saveRDS(imported_data, file = created_file_path)
    cat(paste0("\n\ndatasets ",paste(unique(imported_data$dataset_ID), collapse=" & "), " were processed \nand saved under: ", created_file_path))
    rm(imported_data)
    gc()
    
}


```

