#Filter skeleton
```{r, include=FALSE}

target_folder_base <- "/media/ella/raid5/timelapses/analysis/200127/posture"
save_path <- "/media/ella/raid5/timelapses/analysis/200127/posture/plots"


suffix <- "_with_headext_reordered.rds"

datasets <- c(
  "2019-03-25_18-10-06",#no food
  "2019-11-18_18-43-57",#no food
   "2019-11-20_17-29-55",#no food
  "2019-03-26_19-27-16",#with food
  "2019-03-27_18-24-47",#with food
  # "2019-07-08_18-33-57",#with food
  # "2019-07-09_18-22-34"#with food
  "2019-11-25_17-28-23"#with food
  # "2019-04-23_17-46-08",#daf2
  # "2019-05-07_12-15-40"#daf2
  ## "2019-05-08_14-11-15"#daf2
  # "2019-04-30_14-15-44",#L2
  # "2019-05-04_15-36-42"#L2
  
)

files <- paste0(datasets, suffix)

posture_1 <- readRDS(file=file.path(target_folder_base,files[1]))
posture_2 <- readRDS(file=file.path(target_folder_base,files[2]))
posture_3 <- readRDS(file=file.path(target_folder_base,files[3]))
posture_4 <- readRDS(file=file.path(target_folder_base,files[4]))
posture_5 <- readRDS(file=file.path(target_folder_base,files[5]))
posture_6 <- readRDS(file=file.path(target_folder_base,files[6]))


data_skeleton_with_headext <- rbind(
  posture_1,
  posture_2,
  posture_3,
  posture_4,
  posture_5,
  posture_6
)

```

```{r, include=FALSE}
frames <- 10

skeleton_data_filtered <- data_skeleton_with_headext %>%
  group_by(dataset_ID,tp,TrackID,frame) %>%
  #only postures that have a "YES"
  filter(any(is_head=="YES")) %>%
  mutate(ID = paste0(dataset_ID, "_",tp,"_",TrackID,"_",frame)) %>%
  mutate(dataset_TrackID = paste0(dataset_ID,"_",TrackID)) %>%
  mutate(minutes = 10 + ((tp-1)*8+(tp-1)*0)) %>%
  mutate(hours= minutes/60) %>%
  mutate(hours_rounded= ceiling(hours* 2) / 2) %>%
  group_by(dataset_TrackID,tp) %>%
  mutate(TrackCheck_cleaned = replace_f(TrackCheck, 26*frames)) %>%
  drop_na("TrackCheck_cleaned") %>%
  filter(hours_rounded <= 9) %>%
  ungroup()

skeleton_data_filtered %>%
  group_by(hours_rounded) %>%
  summarise(n = n_distinct(dataset_TrackID))


saveRDS(skeleton_data_filtered, file=file.path(target_folder_base,"200214_Skeletons_filtered.RDS"))
```
