```{r message=FALSE, include=FALSE}


base_path <- "/media/fpreuss/raid5/timelapses/analysis/200703/"
target_path <- file.path(base_path, "data","posture","skeletonized_filtered")

```

```{r message=FALSE, include=FALSE}

files_to_process <- list.files(target_path,"skeletonized_filtered.rds", full.names = TRUE, ignore.case = TRUE)

#define which .rds files to include
files_titles <-  c("1:10_OP50_ske")
files_to_process <- grep(paste0(files_titles,collapse="|"),files_to_process,value = TRUE)

minimal_track_length <- 60

#function to load posture library
#ID to unify posture IDs across annotations
load_skeletonized_filtered_subset <- function(x){
  readRDS(x) %>%
    #estimate 15 minutes as lag before experiment
    mutate(minutes = 15 + ((tp-1)*8+(tp-1)*0)) %>%
    #round to half hour steps
    # mutate(hours_rounded = ceiling(minutes/60*2)/2) %>%
    #round to full hours steps
    mutate(hours_rounded = ceiling(minutes/60)) %>%
    filter(hours_rounded <= 12) %>%
    #summarise by frame and keep location
    mutate(ID = paste0(dataset_ID,"_", tp,"_",TrackID)) %>%
    group_by(ID,frame) %>%
    nest() %>%
    #now calculate for the whole track (== ID)
    group_by(ID) %>%
    #the track should not have any missing frames
    mutate(length_track = n(), length_track2=last(frame)-first(frame)+1) %>%
    filter(length_track == length_track2) %>%
    #filter out tracks that are too short
    filter(length_track > minimal_track_length) %>%
    select(-c(length_track2)) %>%
    group_by(ID) %>%
    sample_n(100)
    # unnest(cols=c(data))
    
}


#load data
skeletonized_filtered_subset <- files_to_process %>%
  map_df(., load_skeletonized_filtered_subset)

```