

```{r, include=FALSE}

#define data paths
target_folder_base <- ("/media/ella/raid5/timelapses")
target_folder_general <- c(#"2019-03-26_19-27-16")
                           #"2019-03-07_17-28-51",
                           #"2019-03-11_17-54-09",
                           #"2019-03-18_18-01-40",
                           #"2019-03-19_17-40-32",
                           "2019-03-25_18-10-06")#no food
                           #"2019-03-27_18-24-47",
                           #"2019-04-15_17-32-23",
                           #"2019-04-23_17-46-08",#daf2
                           #"2019-04-30_14-15-44", #L2
                           #"2019-05-04_15-36-42",#L2
                           #"2019-05-07_12-15-40"#daf2
                           #"2019-05-08_14-11-15",#daf2
                           #"2019-07-08_18-33-57",#1:5 OP50
                           #"2019-07-09_18-22-34"#1:5 OP50
                           #)

target_folder_analysis <- file.path(target_folder_base,target_folder_general, "analysis")


```

#load metadata (for all datasets)
```{r, include=FALSE}
metadata_file <- list.files(file.path(target_folder_base,target_folder_general),pattern=".+\\_metadata.txt$", full.names = TRUE)
metadata <- data.frame(sapply(metadata_file, function (x) read.delim(x,header=FALSE,check.names = FALSE)))
colnames(metadata) <- metadata_file
colnames(metadata) <- as.character(gsub(".+\\/", "",colnames(metadata)))
colnames(metadata) <- as.character(gsub("_metadata.txt", "",colnames(metadata)))

time_elapsed <- apply(metadata,2, function(x) as.numeric(gsub(".+\\s([0-9]+).*", "\\1",x[grepl("Time elapsed.+\\:\\s(.+)",x)])))
time_elapsed <- as.data.frame(time_elapsed)
time_elapsed$dataset <- colnames(metadata)


#timepoint length, in minutes
#attention to divide everything by 60, because this value is entered in seconds
timepoint_length <- apply(metadata,2, function(x) as.numeric(gsub(".+\\:\\s(.+)", "\\1",x[grepl("Timepoint length\\:\\s(.+)\\.",x)])))/60
timepoint_length <- as.data.frame(timepoint_length)
timepoint_length$dataset <- colnames(metadata)


#timestep, in minutes
timestep_length <- apply(metadata,2, function(x) as.numeric(gsub(".+every(.+)minutes\\.", "\\1",x[grepl(".+every(.+)minutes\\.",x)])))
timestep_length <- as.data.frame(timestep_length)
timestep_length$dataset <- colnames(metadata)

#plate type
plate_type <- apply(metadata,2, function(x) gsub(".+\\,(.+)\\,.+", "\\1",x[grepl("Timelapse plate type\\:",x)]))
plate_type <- as.data.frame(plate_type)
plate_type$dataset <- colnames(metadata)

#worm type
worm_type <- apply(metadata,2, function(x) gsub(".+\\:\\s(.+)", "\\1",x[grepl("Used line\\:",x)]))
worm_type <- as.data.frame(worm_type)
worm_type$dataset <- colnames(metadata)

```


#import timelapse data
```{r, include=FALSE}
#list zip files in target_folder_analysis
find_zip_files <- function(target_folder_analysis){
  files <- sort(as.numeric(gsub("(\\d+)\\..+","\\1",list.files(target_folder_analysis,pattern=".zip"))))[1:70]
  file.path(target_folder_analysis,paste0(files, ".csv.zip"))
}



imported_data <-  unlist(map(target_folder_analysis,find_zip_files)) %>%
  map_df(.,function(x) read_csv(x, col_types=cols(),col_names=TRUE) %>% mutate(file_name=x)) %>%
  mutate(dataset_ID = gsub(".+\\/([0-9]+\\-[0-9]+\\-[0-9]+\\_[0-9]+\\-[0-9]+\\-[0-9]+)\\/.+", "\\1",file_name)) %>%
  #replace all whitespaces in column names with "_"
  rename_all(list(~gsub("\\s", "_",.))) %>%
  inner_join(., time_elapsed,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., timepoint_length,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., timestep_length,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., plate_type, by = c("dataset_ID" = "dataset")) %>%
  inner_join(., worm_type, by = c("dataset_ID" = "dataset")) %>%
  mutate(timestep_length = ifelse(timepoint_length > timestep_length, 0,timestep_length-timepoint_length)) %>%
  mutate(minutes = time_elapsed + ((tp-1)*timepoint_length+(tp-1)*timestep_length)) %>%
  mutate(hours= minutes/60) %>%
  na.omit()



#downsampled to for conversion
downsampled_fps <- unique(na.omit(imported_data$downsampled_to))

# save(imported_data, file = file.path(target_folder_analysis,target_folder_general,".rds"))
```


#Skeletonize and estimate heads where possible
```{r message=FALSE, include=FALSE}

tic()
#looks like future and furrr makes this 8x faster
data_skeleton <- imported_data  %>%
  group_by(dataset_ID,tp,TrackID) %>%
  nest() %>%
  mutate(m = map(data,skeleton_direction)) %>%
  select(dataset_ID,tp,TrackID,m) %>%
  unnest() %>%
  group_by(dataset_ID, tp,TrackID,frame) %>%
  nest() %>%
  group_by(dataset_ID, tp,TrackID,frame) %>%
  mutate(mf =map(data,skeleton_frame,dataset_ID,tp,TrackID,frame)) %>%
  select(dataset_ID,tp,TrackID,frame,mf) %>%
  unnest() %>%
  group_by(dataset_ID,tp,TrackID,frame) %>%
  nest() %>%
  mutate(mh = map(data,skeleton_head)) %>%
  select(dataset_ID,tp,TrackID,frame,mh) %>%
  unnest() %>%
  select(-ends_with("1"))
toc()
#save(data_skeleton, file = file.path(target_folder_analysis,target_folder_general,"_with_head.rds"))
```

```{r message=FALSE, include=FALSE}
data_skeleton <- readRDS(file.path(target_folder_analysis,target_folder_general,"_with_head.rds"))
tic()
data_skeleton_with_headext <- data_skeleton %>%
  mutate(head_detected = ifelse(grepl("downsampled | unclear",status),"not yet","NO" )) %>%
  mutate(distance_to_latest_head = NA) %>%
  group_by(dataset_ID, tp,TrackID) %>%
  nest() %>%
  group_by(dataset_ID, tp,TrackID) %>%
  mutate(mhe = map(data,skeleton_head_estimate)) %>%
  select(dataset_ID,tp,TrackID,mhe) %>%
  unnest(cols=c(mhe))
toc()
#save(data_skeleton_headext, file = file.path(target_folder_analysis,target_folder_general,"_with_headext.rds"))
```

```{r message=FALSE, include=FALSE}
data_skeleton_with_headext <- readRDS(file.path(target_folder_analysis,target_folder_general,"_with_headext.rds"))
skeleton_reorder <- function(data){
    if(!is.na(data[nrow(data),"is_head"])){
      data$index <- nrow(data):1
      data
    } else {
      data <- data
    }
}

tic()
data_skeleton_with_headext_reordered <- data_skeleton_with_headext %>%
  group_by(dataset_ID, tp,TrackID,frame) %>%
  nest() %>%
  mutate(mr = map(data,skeleton_reorder)) %>%
  select(dataset_ID,tp,TrackID,frame,mr) %>%
  unnest()
toc()

#save(data_skeleton_headext, file = file.path(target_folder_analysis,target_folder_general,"_with_headext_reordered.rds"))
```



