

```{r, include=FALSE}

#define data paths

target_folder_base <- ("/media/ella/raid5/timelapses")
target_folder_general <- c(
                           # "2019-03-26_19-27-16",  #1:10 N2
                           # "2019-03-11_17-54-09",  #1:10 N2
                           #"2019-03-19_17-40-32",  #1:10 N2
                          #"2019-03-25_18-10-06",   #N2 no food
                           # "2019-03-27_18-24-47",  #1:10 N2
                           "2019-04-23_17-46-08",  #daf2
                           # "2019-04-30_14-15-44",  #L2
                           # "2019-05-04_15-36-42"  #L2
                           "2019-05-07_12-15-40"   #daf2
                           #"2019-07-08_18-33-57",  #1:5 OP50
                           #"2019-07-09_18-22-34"   #1:5 OP50
                           ##"2019-11-14_18-25-04", #1:10 DR47 dauer
                          #"2019-11-18_18-43-57", #no food
                          #"2019-11-20_17-29-55" #no food
                           # "2019-11-25_17-28-23" #1:10 N2
                           )

target_folder_analysis <- file.path(target_folder_base,target_folder_general, "analysis")


```

#load metadata (for all datasets)
```{r, include=FALSE}
metadata_file <- list.files(file.path(target_folder_base,target_folder_general),pattern=".+\\_metadata.txt$", full.names = TRUE)
metadata <- data.frame(sapply(metadata_file, function (x) read.delim(x,header=FALSE,check.names = FALSE)))
colnames(metadata) <- metadata_file
colnames(metadata) <- as.character(gsub(".+\\/", "",colnames(metadata)))
colnames(metadata) <- as.character(gsub("_metadata.txt", "",colnames(metadata)))

time_elapsed <- apply(metadata,2, function(x) as.numeric(gsub(".+\\s([0-9]+).*", "\\1",x[grepl("Time elapsed.+\\:\\s(.+)",x)])))
time_elapsed <- as.data.frame(time_elapsed)
time_elapsed$dataset <- colnames(metadata)


#timepoint length, in minutes
#attention to divide everything by 60, because this value is entered in seconds
timepoint_length <- apply(metadata,2, function(x) as.numeric(gsub(".+\\:\\s(.+)", "\\1",x[grepl("Timepoint length\\:\\s(.+)\\.",x)])))/60
timepoint_length <- as.data.frame(timepoint_length)
timepoint_length$dataset <- colnames(metadata)


#timestep, in minutes
timestep_length <- apply(metadata,2, function(x) as.numeric(gsub(".+every(.+)minutes\\.", "\\1",x[grepl(".+every(.+)minutes\\.",x)])))
timestep_length <- as.data.frame(timestep_length)
timestep_length$dataset <- colnames(metadata)

#plate type
plate_type <- apply(metadata,2, function(x) gsub(".+\\,(.+)\\,.+", "\\1",x[grepl("Timelapse plate type\\:",x)]))
plate_type <- as.data.frame(plate_type)
plate_type$dataset <- colnames(metadata)

#worm type
worm_type <- apply(metadata,2, function(x) gsub(".+\\:\\s(.+)", "\\1",x[grepl("Used line\\:",x)]))
worm_type <- as.data.frame(worm_type)
worm_type$dataset <- colnames(metadata)

```


#import timelapse data
```{r, include=FALSE}
#list zip files in target_folder_analysis
find_zip_files <- function(target_folder_analysis){
  files <- sort(as.numeric(gsub("(\\d+)\\..+","\\1",list.files(target_folder_analysis,pattern=".zip"))))[1:70]
  file.path(target_folder_analysis,paste0(files, ".csv.zip"))
}



imported_data <-  unlist(map(target_folder_analysis,find_zip_files)) %>%
  map_df(.,function(x) read_csv(x, col_types=cols(),col_names=TRUE) %>% mutate(file_name=x)) %>%
  mutate(dataset_ID = gsub(".+\\/([0-9]+\\-[0-9]+\\-[0-9]+\\_[0-9]+\\-[0-9]+\\-[0-9]+)\\/.+", "\\1",file_name)) %>%
  #replace all whitespaces in column names with "_"
  rename_all(list(~gsub("\\s", "_",.))) %>%
  inner_join(., time_elapsed,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., timepoint_length,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., timestep_length,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., plate_type, by = c("dataset_ID" = "dataset")) %>%
  inner_join(., worm_type, by = c("dataset_ID" = "dataset")) %>%
  mutate(timestep_length = ifelse(timepoint_length > timestep_length, 0,timestep_length-timepoint_length)) %>%
  mutate(minutes = time_elapsed + ((tp-1)*timepoint_length+(tp-1)*timestep_length)) %>%
  mutate(hours= minutes/60) %>%
  na.omit()




# save(imported_data, file = file.path(target_folder_analysis,target_folder_general,".rds"))
```

```{r, include=FALSE}
unique(imported_data$dataset_ID)
```

