#set parameters here
```{r, include=FALSE}

#Set the location folder of the raw data (of all experiments you want to plot)
base_path <- "/media/fpreuss/raid5/timelapses/analysis/200703/"
target_path <- file.path(base_path,"data")
save_path <- file.path(base_path,"plots","turns")
dir.create(save_path)
```

#load files for omega turns plotting (raw data files)
```{r, include=FALSE}


#list of .rds files in data folder
files_to_process <- list.files(target_path, "raw_data.rds", full.names = TRUE, ignore.case = TRUE)
files_to_process <- grep("Agar_raw|Agar_with_NAD_raw|daf2_raw|MT14984_raw|OP50_raw|OP50_with_Az_NGM_raw", files_to_process, value=TRUE)


#lower velocity limit for mode == roaming
velocity_r <- 0.01
#upper angle limit for mode == roaming
angle_r <-15
#upper velocity limit for mode == still
# velocity_s <- 0.001


#load all .rds files and append to one data frame ('imported_data')
load_and_summarise <- function(x) {
    readRDS(x) %>%
    mutate(hours = minutes / 60) %>%
    #round per hour
    mutate(hours_rounded = ceiling(hours)) %>%
    filter(hours_rounded <= 12) %>%
    #compute this by tp
    group_by(annotation, dataset_ID, hours_rounded,tp) %>%
    mutate(number_frames = n()) %>%
    mutate(number_of_omega_turns = sum(Prediction == "turn" & Prediction_confidence > 0.8)) %>%
    mutate(omega_turns_per_s = number_of_omega_turns / number_frames / downsampled_to) %>%
    select(annotation, dataset_ID, hours_rounded, number_of_omega_turns,omega_turns_per_s) %>%
    group_by(annotation,dataset_ID, hours_rounded,tp,omega_turns_per_s) %>%
    summarise()
}

imported_data <- files_to_process %>%
  map_df(.,load_and_summarise)
  

created_file_path <- file.path(save_path,"201125_omega_turns.rds")
saveRDS(imported_data, file = created_file_path)

```

#plots for omega turns
```{r, include=FALSE}
imported_data <- readRDS(file.path(save_path,"201125_omega_turns.rds"))
library(wesanderson)

plotting_function <- function(data){
  print(ggplot(data,aes(x=factor(hours_rounded,levels = unique(hours_rounded)),y=omega_turns_per_s))+
  geom_jitter(aes(fill=annotation),shape=21,size=1.5,alpha=0.25,width=0.25)+
  # geom_violin()+
  geom_path(data=. %>% group_by(annotation, hours_rounded) %>% summarise(mean = mean(omega_turns_per_s)), aes(x=hours_rounded,y=mean))+
  xlab("hours") + ylab("omega turns per s")+
  # scale_fill_manual(values=wes_palette(n=5, name="Moonrise3"))+
  theme_classic()+
  facet_wrap(vars(annotation),nrow=1)+
  theme(
    legend.direction="horizontal",
    legend.position = "top",
    strip.background = element_rect(colour = "white", fill = "white"),
    panel.spacing = unit(1, "lines"),
    strip.text.x = element_text(size=7.5,colour = "black", face = "bold"),
    axis.text.x = element_text(size=10),
    axis.title.x = element_text(size=20),
    axis.text.y = element_text(size=10),
    axis.title.y = element_text(size=20),
    axis.ticks=element_line(size=1.5),
    axis.ticks.length=unit(0.25,"cm"),
    axis.line = element_line(colour = 'black', size = 1.5))+
  ggsave(file.path(save_path,paste0("omega_turns_",paste(unique(data$annotation),collapse = "_"),".png")),height=5,width=10)
  )
}


unique(imported_data$annotation)
plotting_function(imported_data %>% filter(annotation == "Agar" | annotation == "OP50 with Az NGM" | annotation == "OP50"| annotation == "MT14984"| annotation == "daf2"))
plotting_function(imported_data %>% filter(annotation == "Agar" | annotation == "Agar with NAD"| annotation == "N2 1:10 OP50" | annotation == "N2 no food" ))
plotting_function(imported_data %>% filter(annotation == "N2 1:10 OP50" | annotation == "N2 1:5 OP50" | annotation == "N2 1:10 OP50 after 6h exit"))
plotting_function(imported_data %>% filter(annotation == "Agar" | annotation == "N2 no food" ))
plotting_function(imported_data)
```


#load data for directional turns (raw data)
```{r, include=FALSE}

#list of .rds files in data folder
files_to_process <- list.files(target_path, "raw_data.rds", full.names = TRUE, ignore.case = TRUE)
files_to_process <- grep("1:10_OP50_after_6h_exit_raw|1:10_OP50_raw|N2_no_food|Agar_raw|Agar_with_NAD_raw|1:5_OP50_raw|N2_empty_after_6h_exit_raw_data", files_to_process, value=TRUE)

count_direction_changes <- function(x){
  mutate(x,direction_changes=sum(head(rle(direction)$lengths, -1) != 1 & tail(rle(direction)$lengths, -1) != 1))
}


skeleton_direction2 <- function(x){
  mutate(x,x_lag=lag(location_x,n=1) - location_x, y_lag = lag(location_y, n=1) - location_y) %>%
    mutate(x_lead=lead(location_x, n=1) - location_x, y_lead=lead(location_y, n=1) - location_y) %>%
    #calculate local distance for velocity (difference between position n and position n-1 second (i.e. 2 frames))
    mutate(local_distance=suppressWarnings(as.numeric(mapply(distance,lag(location_x,n=2),lag(location_y,n=2),location_x,location_y)))) %>%
    # this will result in velocity based on local distance (µm/s)
    mutate(velocity = local_distance*conversion_factor/downsampled_to) %>%
    mutate(x_dir = ifelse(x_lead < 0, "left","right")) %>%
    mutate(y_dir = ifelse(y_lead < 0, "up","down")) %>%
    mutate(direction = paste(x_dir,y_dir,sep="-")) %>%
    # mutate(direction = ifelse(velocity > 10,direction, NA)) %>%
    #only keep the direction when direction and speed > 10µm/s is stable over 2.5 seconds
    mutate(direction = replace_f(direction,4))
    
}



#4
# vector <- c(NA,NA,NA,4,4,5,5,5,5,NA,6,6,6,6,6,7,7,7,7,NA,10,NA,4,4,4,12,12,13,13,NA)
# sum(head(rle(vector)$lengths, -1) != 1 & tail(rle(vector)$lengths, -1) != 1)


downsampled_to <- 2
conversion_factor <- 6.25
#load all .rds files and append to one data frame ('imported_data')
load_and_summarise <- function(x) {
    readRDS(x) %>%
    mutate(hours = minutes / 60) %>%
    #round per hour
    mutate(hours_rounded = ceiling(hours)) %>%
    filter(hours_rounded <= 12) %>%
    select(annotation,dataset_ID,tp,hours_rounded,TrackID,frame,location_x, location_y) %>%
    group_by(dataset_ID,tp,hours_rounded,TrackID) %>%
    #guess direction from centroid movement for every Track
    group_modify(~ skeleton_direction2(.x)) %>%
    #count direction changes within every track (see function above)
    group_modify(~ count_direction_changes(.x)) %>%
    #normalize this by the length of the track to get changes per s
    mutate(number_frames = n()) %>%
    mutate(turns_per_s = direction_changes / number_frames / downsampled_to) %>%
    select(annotation,dataset_ID,tp,hours_rounded,TrackID,direction, turns_per_s,number_frames) %>%
    group_by(annotation,dataset_ID,hours_rounded,tp) %>%
    summarise(mean_turns_per_s = mean(turns_per_s)) %>%
    ungroup()
    
}

imported_data <- files_to_process %>%
  map_df(.,load_and_summarise)

created_file_path <- file.path(save_path,"201005_turns.rds")
saveRDS(imported_data, file = created_file_path)

```


#plots for directional turns
```{r, include=FALSE}
imported_data <- readRDS(file.path(save_path,"201005_turns.rds"))
library(wesanderson)
standarderror <- function(x) sd(x)/sqrt(length(x))



plot <- ggplot(imported_data,aes(x=factor(hours_rounded,levels = unique(hours_rounded)),y=mean_turns_per_s))+
  # geom_boxplot(aes(fill=annotation),lwd=1)+
  geom_point(aes(fill=annotation),shape=21,size=1.5,alpha=0.25)+
  geom_path(data=. %>% group_by(annotation, hours_rounded) %>% summarise(mean = mean(mean_turns_per_s)), aes(x=hours_rounded,y=mean))+
  xlab("hours") + ylab("turns per s")+
  # scale_fill_manual(values=wes_palette(n=6, name="Moonrise3"))+
  theme_classic()+
  facet_wrap(vars(annotation),nrow=1)+
  theme(
    legend.direction="horizontal",
    legend.position = "top",
    strip.background = element_rect(colour = "white", fill = "white"),
    panel.spacing = unit(1, "lines"),
    strip.text.x = element_text(size=7.5,colour = "black", face = "bold"),
    axis.text.x = element_text(size=10),
    axis.title.x = element_text(size=20),
    axis.text.y = element_text(size=10),
    axis.title.y = element_text(size=20),
    axis.ticks=element_line(size=1.5),
    axis.ticks.length=unit(0.25,"cm"),
    axis.line = element_line(colour = 'black', size = 1.5)) +
  ggsave(file.path(save_path,paste0("turns",".png")),height=5,width=20)

plot
```