
##Plots1
```{r, echo=FALSE}

target_folder_base <- "/media/ella/raid5/timelapses/analysis/200127/motion"
save_path <- "/media/ella/raid5/timelapses/analysis/200127/motion/100128_N2with_N2without_daf2_DR47"

motion_1 <- readRDS(file=file.path(target_folder_base,"200127_Motion_1.RDS"))
motion_2 <- readRDS(file=file.path(target_folder_base,"200127_Motion_2.RDS"))
motion_3 <- readRDS(file=file.path(target_folder_base,"200128_Motion_3.RDS"))
motion_4 <- readRDS(file=file.path(target_folder_base,"200127_Motion_4.RDS"))

imported_data <- rbind(motion_1,motion_2,motion_3,motion_4)

```


##Plots1
```{r, echo=FALSE}

downsampled_to <- 2


imported_data %>%
  select(hours, dataset_ID, TrackID) %>%
  group_by(hours, dataset_ID) %>%
  summarise(.,n = n_distinct(TrackID)) %>%
  ggplot(.,aes(x=hours,y=n,fill=dataset_ID,colour=dataset_ID))+
  #scale_colour_manual(values = wes_palette("BottleRocket2"))+
  #geom_line()+
  geom_smooth(method="loess")+
  ylab("Number of tracked worms")+
  theme_classic()

imported_data %>%
  select(hours,dataset_ID, TrackID, Duration_of_track) %>%
  group_by(hours, dataset_ID) %>%
  summarise(., mean_duration =mean(Duration_of_track)/downsampled_to) %>%
  ggplot(.,aes(x=hours,y=mean_duration,fill=dataset_ID,colour=dataset_ID))+
  #scale_colour_manual(values = wes_palette("BottleRocket2"))+
  #geom_line()+
  geom_smooth(method="loess")+
  # geom_hline(yintercept=duration,color="red")+
  ylab("Mean duration of tracks (seconds)")+
  theme_classic()


```


## Plot grouped images for standard parameters
```{r, echo=TRUE}



params <- grep("p\\_.+",colnames(imported_data),value = TRUE)
dfp_for_plotting <- imported_data %>%
  ungroup()%>%
  # filter(!dataset_ID %in% exps_out) %>%
  mutate(dataset_ID = gsub("(.+)\\_.+","\\1",imported_data$dataset_ID))%>%
  group_by(hours,dataset_ID,plate_type)%>%
  unite("experiment", c("dataset_ID","worm_type", "plate_type"), sep= " ") %>%
  group_by(experiment,hours,minutes,tp) %>%
  summarise_at(.vars = params,
               .funs = c(mean_per_minute="mean"))

params <- grep("p\\_.+",colnames(dfp_for_plotting),value = TRUE)
for (i in params){
  print(ggplot(dfp_for_plotting, aes_string(x="hours",y=i))+
          #geom_ribbon(aes(ymin =  median_angle_per_minute - iqr_angle_per_minute, ymax = median_angle_per_minute + iqr_angle_per_minute))+
          geom_line(size=0.5)+
          ggtitle(i)+
          theme_classic()+
          scale_x_continuous(breaks = seq(0, 8, 1),limits = c(0,8))+
          facet_wrap(~experiment)
        #ggsave(paste0(i,".png"))
  )
}


```

##Plot grouped images for standard parameters
```{r, echo=TRUE}



chosen_exps_1 <- c(#with bacteria
  #"2019-03-11_17-54-09",
  #"2019-03-19_17-40-32",
  "2019-03-26_19-27-16",
  "2019-03-27_18-24-47",
  "2019-07-08_18-33-57",
  "2019-07-09_18-22-34",
  "2019-11-25_17-28-23")

chosen_exps_2 <-c("2019-05-07_12-15-40", #daf2 dauer
                  "2019-04-23_17-46-08",
                  "2019-05-08_14-11-15")


chosen_exps_3 <- c("2019-03-25_18-10-06",
                   "2019-11-18_18-43-57",
                   "2019-11-20_17-29-55") #no food

chosen_exps_4 <- c("2019-11-14_18-25-04") # DR47


# chosen_exps_4 <-c("2019-07-08_18-33-57", #1:5 OP50
#                   "2019-07-09_18-22-34") #1:5 OP50

# chosen_exps_5 <-c("2019-04-30_14-15-44", #L2
#                   "2019-05-04_15-36-42")

```

```{r, echo=TRUE}


imported_data_grouped <- imported_data %>%
    filter(dataset_ID %in% chosen_exps_1 | dataset_ID %in% chosen_exps_2 | dataset_ID %in% chosen_exps_3 | dataset_ID %in% chosen_exps_4) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_1, "N2 dauers w. food",NA)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_2, "daf2 dauers",annotation)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_3, "N2 dauers no food",annotation)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_4, "daf-11",annotation)) %>%
    # mutate(annotation = ifelse(dataset_ID %in% chosen_exps_5, "L2",annotation))%>%
    #round per half an hour
    mutate(hours_rounded= ceiling(hours* 2) / 2)

```


```{r, echo=TRUE}

pal <- wes_palette("Darjeeling1",5)[c(1,3,4,5)]


perc_turn <- imported_data_grouped %>%
    group_by(annotation, hours_rounded) %>%
    summarise(mean = mean(p_perc_turn, na.rm = TRUE),
            sd = sd(p_perc_turn, na.rm = TRUE),
            n = n()) %>%
   mutate(se = sd / sqrt(n),
         lower_ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper_ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
    group_by(annotation) %>%
    mutate(mean_number_of_tracks_per_roundedtp_exptype = round(mean(n))) %>%
    ungroup() %>%
    mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))

print(ggplot(perc_turn,aes(x=hours_rounded,y=mean,color=annotation,group=annotation))+
  geom_line(size=1)+
  geom_point()+
  geom_errorbar(width=.1, aes(ymin=lower_ci, ymax=upper_ci))+
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  # scale_y_continuous(limits = c(0,1))+
  scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of turns")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_color_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_turn_line",".png")))
  
)

print(ggplot(perc_turn,aes(x=hours_rounded,y=mean,fill=annotation))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(position=position_dodge(.45),width=.1, aes(ymin=lower_ci, ymax=upper_ci),color="white")+
  # geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7.3),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of turns")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_fill_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_turn_bar",".png")))
)

```


```{r, echo=TRUE}


perc_straight <- imported_data_grouped %>%
    filter(annotation %in% c("N2 dauers no food","N2 dauers w. food")) %>%
    group_by(annotation, hours_rounded) %>%
    summarise(mean = mean(p_perc_straight, na.rm = TRUE),
            sd = sd(p_perc_straight, na.rm = TRUE),
            n = n()) %>%
   mutate(se = sd / sqrt(n),
         lower_ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper_ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
    group_by(annotation) %>%
    mutate(mean_number_of_tracks_per_roundedtp_exptype = round(mean(n))) %>%
    ungroup() %>%
    mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))
 
pal <- wes_palette("Darjeeling1",5)[c(3,5)]
          
print(ggplot(perc_straight,aes(x=hours_rounded,y=mean,color=annotation,group=annotation,palette = "jco"))+
  geom_line(size=1)+
  geom_point()+
  geom_errorbar(width=.1, aes(ymin=lower_ci, ymax=upper_ci))+
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
  scale_y_continuous(limits = c(0,1))+
  xlab("hours") + ylab("relative occurence of straight movement")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_color_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_straight_line",".png"))) 
)

print(ggplot(perc_straight,aes(x=hours_rounded,y=mean,fill=annotation))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(position=position_dodge(.5),width=.1, aes(ymin=lower_ci, ymax=upper_ci),color="white")+
  # geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7.3),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of straight movement")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_fill_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_straight_bar",".png")))
)

```

```{r, echo=TRUE}
perc_pause <- imported_data_grouped %>%
    group_by(annotation, hours_rounded) %>%
    summarise(mean = mean(p_perc_pause, na.rm = TRUE),
            sd = sd(p_perc_pause, na.rm = TRUE),
            n = n()) %>%
   mutate(se = sd / sqrt(n),
         lower_ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper_ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
    group_by(annotation) %>%
    mutate(mean_number_of_tracks_per_roundedtp_exptype = round(mean(n))) %>%
    ungroup() %>%
    mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))

pal <- wes_palette("Darjeeling1",5)[c(1,2,3,5)]

print(ggplot(perc_pause,aes(x=hours_rounded,y=mean,color=annotation,group=annotation,palette = "jco"))+
  geom_line(size=1)+
  geom_point()+
  geom_errorbar(width=.1, aes(ymin=lower_ci, ymax=upper_ci))+
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_y_continuous(limits = c(0,1))+
  scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of pausing")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_color_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_pause_line",".png")))
)

print(ggplot(perc_pause,aes(x=hours_rounded,y=mean,fill=annotation))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(position=position_dodge(.5),width=.1, aes(ymin=lower_ci, ymax=upper_ci),color="white")+
  # geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7.3),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of pausing")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_fill_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_pause_bar",".png")))
)

```


```{r, echo=TRUE}
perc_omega <- imported_data_grouped %>%
    group_by(annotation, hours_rounded) %>%
    summarise(mean = mean(p_perc_omega_turn, na.rm = TRUE),
            sd = sd(p_perc_omega_turn, na.rm = TRUE),
            n = n()) %>%
   mutate(se = sd / sqrt(n),
         lower_ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper_ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
    group_by(annotation) %>%
    mutate(mean_number_of_tracks_per_roundedtp_exptype = round(mean(n))) %>%
    ungroup() %>%
    mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))


pal <- wes_palette("Darjeeling1",5)[c(1,2,3,5)]

print(ggplot(perc_omega,aes(x=hours_rounded,y=mean,color=annotation,group=annotation,palette = "jco"))+
  geom_line(size=1)+
  geom_point()+
  geom_errorbar(width=.1, aes(ymin=lower_ci, ymax=upper_ci))+
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of omega turns")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_color_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_omega_line",".png")))
)

print(ggplot(perc_omega,aes(x=hours_rounded,y=mean,fill=annotation))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(position=position_dodge(.5),width=.1, aes(ymin=lower_ci, ymax=upper_ci),color="white")+
  # geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7.3),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("relative occurence of omega turns")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_fill_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("perc_omega_line",".png")))
)

```

```{r, echo=TRUE}
mean_velocity <- imported_data_grouped %>%
    group_by(annotation, hours_rounded) %>%
    summarise(mean = mean(p_mean_velocity, na.rm = TRUE),
            sd = sd(p_mean_velocity, na.rm = TRUE),
            n = n()) %>%
   mutate(se = sd / sqrt(n),
         lower_ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper_ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
    group_by(annotation) %>%
    mutate(mean_number_of_tracks_per_roundedtp_exptype = round(mean(n))) %>%
    ungroup() %>%
    mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))

pal <- wes_palette("Darjeeling1",5)[c(1,2,3,5)]


print(ggplot(mean_velocity,aes(x=hours_rounded,y=mean,color=annotation,group=annotation,palette = "jco"))+
  geom_line(size=1)+
  geom_point()+
  geom_errorbar(width=.1, aes(ymin=lower_ci, ymax=upper_ci))+
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("average worm velocity (µm/s)")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_color_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("mean_velocity_line",".png")))
)  

print(ggplot(mean_velocity,aes(x=hours_rounded,y=mean,fill=annotation))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(position=position_dodge(.5),width=.1, aes(ymin=lower_ci, ymax=upper_ci),color="white")+
  # geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7.3),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("average worm velocity (µm/s)")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_fill_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("mean_velocity_bar",".png")))
)
```

```{r, echo=TRUE}
mean_angle <- imported_data_grouped %>%
    filter(annotation %in% c("N2 dauers no food","N2 dauers w. food")) %>%
    group_by(annotation, hours_rounded) %>%
    summarise(mean = mean(p_mean_angle, na.rm = TRUE),
            sd = sd(p_mean_angle, na.rm = TRUE),
            n = n()) %>%
   mutate(se = sd / sqrt(n),
         lower_ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper_ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
    group_by(annotation) %>%
    mutate(mean_number_of_tracks_per_roundedtp_exptype = round(mean(n))) %>%
    ungroup() %>%
    mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))

pal <- wes_palette("Darjeeling1",5)[c(3,5)]


print(ggplot(mean_angle,aes(x=hours_rounded,y=mean,color=annotation,group=annotation))+
  geom_line(size=1)+
  geom_point()+
  geom_errorbar(width=.1, aes(ymin=lower_ci, ymax=upper_ci))+
  geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("Average worm path angle (degrees)")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_color_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("mean_angle_line",".png")))
)

print(ggplot(mean_angle,aes(x=hours_rounded,y=mean,fill=annotation))+
  geom_bar(stat="identity", position=position_dodge())+
  geom_errorbar(position=position_dodge(.5),width=.1, aes(ymin=lower_ci, ymax=upper_ci),color="white")+
  # geom_ribbon(aes(ymin=lower_ci, ymax=upper_ci), fill="white",linetype = 0, alpha=0.2)+
  # ggtitle(paste0(i," with standard error of the mean"))+
  scale_x_continuous(limits = c(0,7.3),breaks = seq(0, 7, 1))+
  xlab("hours") + ylab("Average worm path angle (degrees)")+
  theme_black()+
  theme(legend.direction="vertical")+
  scale_fill_manual(values =pal)+
  #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
  ggsave(file.path(save_path,paste0("mean_angle_bar",".png")))
)
```


```{r, echo=TRUE}

boxplot <- imported_data_grouped %>%
  filter(annotation %in% c("N2 dauers no food","N2 dauers w. food")) %>%
  filter(hours_rounded < 7.5)
  

pal <- wes_palette("Darjeeling1",5)[c(3,5)]


ggplot(boxplot,aes(x=as.character(hours_rounded),y=p_mean_angle,fill=annotation))+
      # geom_boxplot()+
      geom_violin(draw_quantiles=1)+
      #ggtitle(paste0(i," with standard error of the mean"))+
      # scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))
      # xlab("hours") + ylab("Average turns per s")+
      theme_black()+
      theme(legend.direction="vertical")+
      scale_fill_manual(values =pal)

ggplot(boxplot,aes(x=as.character(hours_rounded),y=p_mean_velocity,fill=annotation))+
      # geom_boxplot()+
      geom_violin(draw_quantiles=1)+
      #ggtitle(paste0(i," with standard error of the mean"))+
      # scale_y_continuous(limits = c(0,0.2))+
      # xlab("hours") + ylab("Average turns per s")+
      theme_black()+
      theme(legend.direction="vertical")+
      scale_fill_manual(values =pal)



```




```{r, echo=TRUE}
heatmap <- imported_data_grouped %>%
  #filter(annotation %in% c("N2 dauers w. food")) %>%
  filter(hours_rounded < 7.5)

ggplot(heatmap,aes(x = p_mean_angle, y = p_mean_velocity))+
  stat_density_2d(aes(fill = ..ndensity..),contour=FALSE,geom="raster")+
  scale_fill_viridis(option = "inferno")+
  scale_x_log10(limits=c(1,180))+
  scale_y_log10()+
  theme_black()+
  coord_fixed(ratio = 1)+
  facet_wrap(annotation+hours_rounded ~ ., nrow=length(unique(heatmap$annotation)), ncol= 14)+
  ggsave(file.path(save_path,paste0("roaming_dwelling_heatmap",".png")),height=10,width=15)

```

```{r, echo=TRUE}

pal <- wes_palette("Darjeeling1",5)[c(3,5)]

heatmap <- imported_data_grouped %>%
  # filter(annotation %in% c("N2 dauers w. food")) %>%
  filter(hours_rounded < 7.5) %>%
  mutate(ratio = p_mean_velocity/p_mean_angle) %>%
  mutate(behavioral_state=ifelse(ratio > 1, "roaming","dwelling")) %>%
  group_by(annotation,hours_rounded,behavioral_state,dataset_ID) %>%
  summarise(counts=n()) %>%
  group_by(annotation,hours_rounded,dataset_ID) %>%
  mutate(sum=sum(counts)) %>%
  mutate(perc = counts/sum)

# ggplot(imported_data_grouped,aes(x = p_mean_angle, y = p_mean_velocity,color=behavioral_state))+
#   geom_point(alpha=0.1)+
#   scale_x_log10(limits=c(1,180))+
#   scale_y_log10()+
#   theme_black()+
#   coord_fixed(ratio = 1)

ggplot(heatmap,aes(x=as.character(hours_rounded),y=perc,fill=behavioral_state,color=behavioral_state))+
      geom_point(alpha=0.05)+
      geom_boxplot(outlier.shape = NA)+
      # geom_violin(draw_quantiles=1)+
      #ggtitle(paste0(i," with standard error of the mean"))+
      # scale_y_continuous(limits = c(0,0.2))+
      xlab("hours") + ylab("Relative occurence of \nbehavioral state")+
      facet_wrap(annotation ~ .)+
      theme_black()+
      theme(legend.direction="vertical")+
      scale_fill_manual(values =pal)+
      scale_color_manual(values=pal)+
      coord_fixed(ratio = 10)+
      ggsave(file.path(save_path,paste0("roaming_dwelling_relative",".png")),height=10,width=15)
```

```{r, echo=TRUE}
test <- MASS::geyser

threedimensionalmap <- imported_data_grouped %>%
  filter(annotation %in% c("N2 dauers w. food"))

data <- data.frame(threedimensionalmap$p_mean_angle,threedimensionalmap$p_mean_velocity)
colnames(data) <- c("mean_angle","mean_velocity")

kd <- with(data, MASS::kde2d(mean_angle,mean_velocity, n = 50))
p <- plot_ly(x = kd$x, y = kd$y, z = kd$z) %>% add_surface()
p
chart_link = api_create(p, filename="surface-2")
chart_link

```


