  
#Define locations and datasets to include
```{r, echo=FALSE}

#define base path
base_path <- "~/Desktop/data"
target_folder<- file.path(base_path, "raw_data")
files_to_process <- list.files(target_folder,"raw_data", full.names = TRUE, ignore.case = TRUE)

selected_annotation <- "OP50"
files_to_process <- grep(selected_annotation,files_to_process,value = TRUE)
conversion_factor <- 6.25

#define save path
save_path <- file.path(base_path,"plots","motion_examples")
dir.create(save_path)

```

#Load data
```{r, echo=FALSE}
#select which timepoints
selected_hours <- c(4,12)


#load data
imported_data <- readRDS(files_to_process) %>%
  #estimate 15 minutes as lag before experiment
  mutate(minutes = 15 + ((tp-1)*8+(tp-1)*0)) %>%
  #round to full hours steps
  mutate(hours_rounded = ceiling(minutes/60)) %>%
  filter(hours_rounded %in% selected_hours)

```

#process data
```{r, echo=FALSE}
#only tracks longer than 1 mins (if 2fps)
fps <- 2
#120secs
minimal_track_length_s <- 60
minimal_track_length_f <- minimal_track_length_s * fps

#only tracks longer than 3 mins (if 2fps)
#240secs
maximal_track_length_s <- 180
maximal_track_length_f <- maximal_track_length_s * fps

#pixel to µm conversion
#this is with magnifaction 3.2
conversion_factor <- 6.25

#set parameters
#We record at 2fps
offset =2 #== 1 seconds
max_gaps = 0

#calculate track angle and velocity for the selected data
data_for_plotting <- imported_data %>%
  # only tracks with less gaps than max_gaps allowed 
  filter(Number_of_gaps <= max_gaps) %>%
  #ID is track specific!
  mutate(ID = paste0(dataset_ID,"_",tp,"_",TrackID)) %>%
  group_by(ID) %>%
  #calculate track length (in frames)
  mutate(track_length = last(frame) - first(frame)) %>%
  #only tracks with a certain length (here, given in frames)
  filter(track_length >= minimal_track_length_f & track_length <= maximal_track_length_f) %>%
  mutate(x_lag=lag(location_x,n=offset) - location_x, y_lag = lag(location_y, n=offset) - location_y) %>%
  mutate(x_lead=lead(location_x, n=) - location_x, y_lead=lead(location_y, n=offset) - location_y) %>%
  # calculate the angle and convert to degrees
  mutate(angle_track = suppressWarnings(180 - (as.numeric(mapply(angle1,x_lag,y_lag,x_lead,y_lead)))*180/pi)) %>%
  # measure distance between current point and 1 second before
  mutate(local_distance=suppressWarnings(as.numeric(mapply(distance,lag(location_x,n=2),lag(location_y,n=2),location_x,location_y)))) %>%
  # this will result in velocity based on local distance (µm/s)
  mutate(velocity = local_distance*conversion_factor/2) %>%
  #identify first and last location
  mutate(first_location_x = first(location_x),first_location_y = first(location_y)) %>%
  mutate(last_location_x = last(location_x),last_location_y = last(location_y)) %>%
  #calculate traveled distance (between first and last point)
  mutate(traveled_distance = distance(first_location_x,first_location_y,last_location_x,last_location_y)) %>%
  #center location
  mutate(location_x_centered = location_x-first_location_x, location_y_centered = location_y-first_location_y) %>%
  ungroup() %>%
  select(ID,annotation,dataset_ID, tp, TrackID,frame,hours_rounded, x_lag, y_lead, y_lag, y_lead, location_x, location_y, traveled_distance,angle_track, local_distance, velocity, track_length, first_location_x, first_location_y, location_x_centered, location_y_centered, track_length) %>%
  # all calculations now done per individual worm (==track)
  # (uniqueness ensured by ID (dataset, tp and TrackID))
  group_by(hours_rounded) %>%
  #average track displacement per hour
  mutate(average_traveled_distance = mean(traveled_distance,na.rm=FALSE)) %>%
  ungroup()


data_for_plotting %>%
  group_by(ID,hours_rounded,average_traveled_distance) %>%
  nest() %>%
  group_by(hours_rounded,average_traveled_distance) %>%
  summarise(n=n())


```

#subset data
```{r, echo=FALSE}

#How many tracks are shown?
numbers_of_displayed_tracks <- 10

#previously selected tracks
selected_tracks <- c("2020-06-25_17-58-07_22_track_9",
                     "2020-06-25_17-58-07_23_track_234",
                     "2020-06-25_17-58-07_26_track_27",
                     "2020-06-25_17-58-07_28_track_116",
                     "2020-06-23_17-58-40_22_track_90",
                     "2020-06-25_17-58-07_22_track_136",
                     "2020-06-22_17-58-37_22_track_107",
                     "2020-06-23_17-58-40_22_track_13",
                     "2020-06-23_17-58-40_23_track_242",
                     "2020-06-23_17-58-40_28_track_42",
                     "2020-06-23_17-58-40_82_track_94",
                     "2020-06-22_17-58-37_88_track_59",
                     "2020-06-22_17-58-37_82_track_5",
                     "2020-06-23_17-58-40_86_track_124",
                     "2020-06-22_17-58-37_85_track_12",
                     "2020-06-23_17-58-40_86_track_15",
                     "2020-06-25_17-58-07_87_track_21",
                     "2020-06-22_17-58-37_84_track_49",
                     "2020-06-23_17-58-40_88_track_76",
                     "2020-06-25_17-58-07_87_track_8"
                    )

#sample random tracks
#how many tracks is defined by "numbers_of_displayed_track" variable
data_for_plotting_sub <- data_for_plotting %>%
  filter(ID %in% selected_tracks)
  # group_by(hours_rounded) %>%
  # #order by total distance travelled (within hours to be compared)
  # arrange(desc(Track_displacement), .by_group=TRUE) %>%
  # distinct(ID,hours_rounded) %>%
  # group_by(hours_rounded) %>%
  # #for each hour to be compared take the 10 tracks with the longest traveled distance
  # # slice(1:numbers_of_displayed_tracks) %>%
  # sample_n(numbers_of_displayed_tracks) %>%
  # ungroup() %>%
  # select(ID) %>%
  # left_join(data_for_plotting, by="ID")


```

#computing a scale bar
```{r, echo=FALSE}
#computing a scale bar
#get the number of pixels for 1 mm
number_of_pixels <- 1000 / conversion_factor

#where should the line be located in the plot
location_x_centered <- seq(101, 100+number_of_pixels)
location_y_centered <- rep(-600, number_of_pixels)

#create a dataframe for the scale bar data 
hours_rounded <- rep(selected_hours,number_of_pixels/2)
ID <- paste0("scale_",hours_rounded)
scale_bar <- data.frame(location_x_centered , location_y_centered,ID, hours_rounded)
#add rows of scale bar data to the original dataset
data_for_plotting_sub <- bind_rows(data_for_plotting_sub, scale_bar)

```

#function for computing circle
```{r, echo=FALSE}
#function for plotting a circle at a center with a fixed diameter
circleFun <- function(center,diameter, npoints = 100){
    r = diameter / 2
    tt <- seq(0,2*pi,length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(location_x_centered = xx, location_y_centered = yy))
}


#
circle_dat_first <- circleFun(c(0,0),unique(data_for_plotting_sub$average_traveled_distance)[1],npoints = 100) %>%
  mutate(hours_rounded = unique(data_for_plotting_sub$hours_rounded)[1])
circle_dat_second <- circleFun(c(0,0),unique(data_for_plotting_sub$average_traveled_distance)[2],npoints = 100) %>%
  mutate(hours_rounded = unique(data_for_plotting_sub$hours_rounded)[2])

#add rows of circle data to the original dataset
circle_data <- bind_rows(circle_dat_first,circle_dat_second)
```


```{r, echo=FALSE}

#tracks colored by ID
ggplot()+
  geom_polygon(data=circle_data,aes(x=location_x_centered, y=location_y_centered),fill="lightgrey",alpha=0.5)+
  geom_path(data=data_for_plotting_sub,aes(x=location_x_centered, y=location_y_centered,group=ID,color=ID),size=0.75)+
  theme(aspect.ratio = 800/800)+
  scale_x_continuous(limits= c(-799,799))+
  scale_y_continuous(limits= c(-799,799))+
  theme_classic()+
  facet_wrap(vars(hours_rounded),ncol=2)+
  theme(legend.position = "none")+
  ggtitle(paste0(selected_annotation,"\n", "hours: ", paste0(selected_hours,collapse=" & "), "\n", minimal_track_length_s/60, " - ", maximal_track_length_s/60, " mins","\n", numbers_of_displayed_tracks, " tracks." ))+
  ggsave(file.path(save_path,paste0(selected_annotation,"_hours_", paste0(selected_hours,collapse="_"),"_all_tracks_centered",".png")),height = 6,width= 9.5,dpi=300)


#tracks individual
data_for_plotting_sub_sub <- data_for_plotting_sub %>%
  #filter out scale bar pixels
  filter(ID != "scale") %>%
  group_by(hours_rounded) %>%
  #order by total distance travelled (within hours to be compared)
  arrange(desc(traveled_distance), .by_group=TRUE) %>%
  distinct(ID,hours_rounded) %>%
  group_by(hours_rounded) %>%
  #for each hour to be compared take the 10 tracks with the longest traveled distance
  slice(1:10) %>%
  ungroup() %>%
  select(ID) %>%
  left_join(data_for_plotting_sub, by="ID") %>%
  group_by(ID) %>%
  #mean angle curvature per track
  mutate(mean_angle_track = mean(angle_track, na.rm=TRUE)) %>%
  mutate(is_first = ifelse(first(frame) == frame, "first", NA))%>%
  mutate(is_end = ifelse(last(frame) == frame, "end", NA)) %>%
  mutate(ID = paste0(ID, "\n",round(track_length/fps/60,1)))

data_for_plotting_sub_sub <- bind_rows(data_for_plotting_sub_sub, scale_bar)

ggplot(data_for_plotting_sub_sub)+
  geom_path(aes(x=location_x_centered, y=location_y_centered,group=ID),size=0.5)+
  geom_point(data=filter(data_for_plotting_sub_sub,is_first == "first"),aes(x=location_x_centered, y=location_y_centered),color="red")+
  geom_point(data=filter(data_for_plotting_sub_sub,is_end == "end"),aes(x=location_x_centered, y=location_y_centered),color="orange")+
  theme_classic()+
  facet_wrap(vars(hours_rounded,ID),nrow = 2)+
  coord_equal()+
  # theme(aspect.ratio = 800/800)+
  # scale_x_continuous(limits= c(-799,799))+
  # scale_y_continuous(limits= c(-799,799))+
  ggtitle(paste0(selected_annotation,"\n", "hours: ", paste0(selected_hours,collapse=" & "), "\n", minimal_track_length_s/60, " - ", maximal_track_length_s/60, " mins","\n", numbers_of_displayed_tracks, " tracks." ))+
  ggsave(file.path(save_path,paste0(selected_annotation,"_hours_", paste0(selected_hours,collapse="_"),"_all_tracks_individual",".png")),height = 30,width= 40,unit="cm",dpi=300)

```
