

#Bin data in time bins (per hour) & sample equal number from each bin
```{r, include=FALSE}
bin_data_sampled <- skeleton_data_cluster %>%
   # filter(index %in% 3:26) %>%
   filter(tp %in% 1:40) %>%
   group_by(dataset_ID,tp,TrackID,frame) %>%
   nest() %>%
   mutate(time = ifelse(tp < 8,"<1h",NA)) %>%
   mutate(time = ifelse(tp >= 8 & tp < 16,"<2h",time)) %>%
   mutate(time = ifelse(tp >= 16 & tp < 24,"<3h",time)) %>%
   mutate(time = ifelse(tp >= 24 & tp < 32,"<4h",time)) %>%
   mutate(time = ifelse(tp >= 32 & tp < 40,"<5h",time)) %>%
   group_by(time) %>%
   sample_n(2000) %>%
   mutate(ID_number= 1:n()) %>%
   unnest(cols=c(data)) %>%
   drop_na("time")
```


#Plot averaged angles for each bin, adding one more posture each image
```{r, include=FALSE}


for(i in seq(1:500)){
   
   to_plot <- bin_data_sampled %>%
    group_by(time)%>%
    filter(ID_number %in% 1:i)
 
   ggplot(to_plot, aes(x=angle,y=index))+
     stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
     geom_point(data=bin_data_sampled %>% filter(ID_number == i ),aes(x=angle,y=index,color=angle),alpha=1, size=2)+
     facet_grid(~time)+
     scale_fill_viridis()+
     scale_color_gradient2(low = "cornflowerblue", mid = "white",
                            high = "brown2",midpoint=0,limits=c(-1,1),na.value="grey") +
     # scale_fill_distiller(palette= "Spectral", direction=1) +
     # scale_fill_viridis_c(option = "plasma") +
     # scale_fill_distiller(palette = "Spectral")+
     # scale_fill_distiller(palette=4, direction=1) +
     scale_y_continuous(trans = "reverse")+
     scale_x_continuous(limits=c(-1,1))+
     theme_classic2()
 
   ggsave(file.path(base_location,"plots",paste0("averaged_angles_examples_",i,".png")),width=12,height=9)
}
```


#Plot distribution for each angle in each time bin
```{r, include=FALSE}
ggplot(bin_data_sampled,aes(x=time,y=angle,group=time,fill=time))+
  # geom_boxplot()+
  geom_violin()+
  # geom_boxplot()+
  coord_flip()+
  scale_y_continuous(limits=c(-1,1))+
  theme_black()+
  theme(legend.position = "top")
```


