---
title: "WormObserver_analysis_complete"
output: html_document
---

#define data paths
```{r, include=FALSE}
target_folder_base <- ("/media/ella/raid5/timelapses")
target_folder_general <- c(#"2019-03-26_19-27-16")
                           #"2019-03-07_17-28-51",
                           #"2019-03-11_17-54-09",
                           #"2019-03-18_18-01-40",
                           #"2019-03-19_17-40-32",
                           "2019-03-25_18-10-06")#no food
                           #"2019-03-27_18-24-47",
                           #"2019-04-15_17-32-23",
                           #"2019-04-23_17-46-08",#daf2
                           #"2019-04-30_14-15-44", #L2
                           #"2019-05-04_15-36-42",#L2
                           #"2019-05-07_12-15-40"#daf2
                           #"2019-05-08_14-11-15",#daf2
                           #"2019-07-08_18-33-57",#1:5 OP50
                           #"2019-07-09_18-22-34"#1:5 OP50
                           #)

target_folder_analysis <- file.path(target_folder_base,target_folder_general, "analysis")


```

#load metadata (for all datasets)
```{r, include=FALSE}
metadata_file <- list.files(file.path(target_folder_base,target_folder_general),pattern=".+\\_metadata.txt$", full.names = TRUE)
metadata <- data.frame(sapply(metadata_file, function (x) read.delim(x,header=FALSE,check.names = FALSE)))
colnames(metadata) <- metadata_file
colnames(metadata) <- as.character(gsub(".+\\/", "",colnames(metadata)))
colnames(metadata) <- as.character(gsub("_metadata.txt", "",colnames(metadata)))

time_elapsed <- apply(metadata,2, function(x) as.numeric(gsub(".+\\s([0-9]+).*", "\\1",x[grepl("Time elapsed.+\\:\\s(.+)",x)])))
time_elapsed <- as.data.frame(time_elapsed)
time_elapsed$dataset <- colnames(metadata)


#timepoint length, in minutes
#attention to divide everything by 60, because this value is entered in seconds
timepoint_length <- apply(metadata,2, function(x) as.numeric(gsub(".+\\:\\s(.+)", "\\1",x[grepl("Timepoint length\\:\\s(.+)\\.",x)])))/60
timepoint_length <- as.data.frame(timepoint_length)
timepoint_length$dataset <- colnames(metadata)


#timestep, in minutes
timestep_length <- apply(metadata,2, function(x) as.numeric(gsub(".+every(.+)minutes\\.", "\\1",x[grepl(".+every(.+)minutes\\.",x)])))
timestep_length <- as.data.frame(timestep_length)
timestep_length$dataset <- colnames(metadata)

#plate type
plate_type <- apply(metadata,2, function(x) gsub(".+\\,(.+)\\,.+", "\\1",x[grepl("Timelapse plate type\\:",x)]))
plate_type <- as.data.frame(plate_type)
plate_type$dataset <- colnames(metadata)

#worm type
worm_type <- apply(metadata,2, function(x) gsub(".+\\:\\s(.+)", "\\1",x[grepl("Used line\\:",x)]))
worm_type <- as.data.frame(worm_type)
worm_type$dataset <- colnames(metadata)

```


#import timelapse data
```{r, include=FALSE}
#list zip files in target_folder_analysis
find_zip_files <- function(target_folder_analysis){
  files <- sort(as.numeric(gsub("(\\d+)\\..+","\\1",list.files(target_folder_analysis,pattern=".zip"))))[1:70]
  file.path(target_folder_analysis,paste0(files, ".csv.zip"))
}



imported_data <-  unlist(map(target_folder_analysis,find_zip_files)) %>%
  map_df(.,function(x) read_csv(x, col_types=cols(),col_names=TRUE) %>% mutate(file_name=x)) %>%
  mutate(dataset_ID = gsub(".+\\/([0-9]+\\-[0-9]+\\-[0-9]+\\_[0-9]+\\-[0-9]+\\-[0-9]+)\\/.+", "\\1",file_name)) %>%
  #replace all whitespaces in column names with "_"
  rename_all(list(~gsub("\\s", "_",.))) %>%
  inner_join(., time_elapsed,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., timepoint_length,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., timestep_length,by = c("dataset_ID" = "dataset")) %>%
  inner_join(., plate_type, by = c("dataset_ID" = "dataset")) %>%
  inner_join(., worm_type, by = c("dataset_ID" = "dataset")) %>%
  mutate(timestep_length = ifelse(timepoint_length > timestep_length, 0,timestep_length-timepoint_length)) %>%
  mutate(minutes = time_elapsed + ((tp-1)*timepoint_length+(tp-1)*timestep_length)) %>%
  mutate(hours= minutes/60) %>%
  na.omit()



#downsampled to for conversion
downsampled_fps <- unique(na.omit(imported_data$downsampled_to))

#save(data, file = paste0("6experiments","_","1-50tp",".RData"))
save(imported_data, file = file.path(target_folder_base,"analysis","191122",paste0("2019-03-26_19-27-16","_","70tps","_","0-900",".RData")))
```


#Skeletonize and estimate heads where possible
```{r message=FALSE, include=FALSE}

tic()
#looks like future and furrr makes this 8x faster
data_skeleton <- imported_data  %>%
  group_by(dataset_ID,tp,TrackID) %>%
  nest() %>%
  mutate(m = map(data,skeleton_direction)) %>%
  select(dataset_ID,tp,TrackID,m) %>%
  unnest() %>%
  group_by(dataset_ID, tp,TrackID,frame) %>%
  nest() %>%
  group_by(dataset_ID, tp,TrackID,frame) %>%
  mutate(mf =map(data,skeleton_frame,dataset_ID,tp,TrackID,frame)) %>%
  select(dataset_ID,tp,TrackID,frame,mf) %>%
  unnest() %>%
  group_by(dataset_ID,tp,TrackID,frame) %>%
  nest() %>%
  mutate(mh = map(data,skeleton_head)) %>%
  select(dataset_ID,tp,TrackID,frame,mh) %>%
  unnest() %>%
  select(-ends_with("1"))
toc()
save(data_skeleton, file = file.path(target_folder_analysis,target_folder_general,"_with_head.rds"))
```

```{r message=FALSE, include=FALSE}
data_skeleton <- readRDS(file.path(target_folder_analysis,target_folder_general,"_with_head.rds"))
tic()
data_skeleton_with_headext <- data_skeleton %>%
  mutate(head_detected = ifelse(grepl("downsampled | unclear",status),"not yet","NO" )) %>%
  mutate(distance_to_latest_head = NA) %>%
  group_by(dataset_ID, tp,TrackID) %>%
  nest() %>%
  group_by(dataset_ID, tp,TrackID) %>%
  mutate(mhe = map(data,skeleton_head_estimate)) %>%
  select(dataset_ID,tp,TrackID,mhe) %>%
  unnest(cols=c(mhe))
toc()
#save(data_skeleton_headext, file = file.path(target_folder_analysis,target_folder_general,"_with_headext.rds"))
```

```{r message=FALSE, include=FALSE}
data_skeleton_with_headext <- readRDS(file.path(target_folder_analysis,target_folder_general,"_with_headext.rds"))
skeleton_reorder <- function(data){
    if(!is.na(data[nrow(data),"is_head"])){
      data$index <- nrow(data):1
      data
    } else {
      data <- data
    }
}

tic()
data_skeleton_with_headext_reordered <- data_skeleton_with_headext %>%
  group_by(dataset_ID, tp,TrackID,frame) %>%
  nest() %>%
  mutate(mr = map(data,skeleton_reorder)) %>%
  select(dataset_ID,tp,TrackID,frame,mr) %>%
  unnest()
toc()

#save(data_skeleton_headext, file = file.path(target_folder_analysis,target_folder_general,"_with_headext_reordered.rds"))
```



##set parameters here
```{r, include=FALSE}
#pixel to mm conversion
conversion_factor <- 6.25

#set parameters
offset =8 #== 4 seconds
max_gaps = 0 
duration = 20 #==10 seconds
binning_factor = 8 #==4 seconds

#conversion_factor,offset,binning_factor,max_gaps,duration
dfp <- calculate_overview_statistics(imported_data,conversion_factor,offset,binning_factor,max_gaps,duration)



```


```{r, include=FALSE}
#which_tracks,which_track,offset,binning_factor,conversion_factor,time_input_type,time_input,which_dataset,max_number_gaps,duration,selected_frame,color_path,image
plot_image_with_path("current_frame","track_4",8,binning_factor,conversion_factor,"minutes",18,"2019-03-26_19-27-16",0,30*2,10,"ID","no_image")
#plot_image_with_path_centered("all_frames",4*2,conversion_factor,"minutes",18,"2019-03-06_17-56-39",0,50,30*2,10,"ID","no_image")

plot_single_path_states("track_2",conversion_factor,offset,binning_factor,"minutes",700,100,"2019-03-06_17-56-39",max_gaps,duration,"path_class_binned","no_image")+
  ggsave("Path_4.png")
plot_single_path_states("track_1",conversion_factor,offset,binning_factor,"minutes",1,100,"2019-03-06_17-56-39",max_gaps,duration,"path_class_binned","no_image")


p2 <- ggplot(data_for_plotting,aes(x=frame, y=local_distance,xend=lead(frame),yend=lead(local_distance),color=state_binned))+
  geom_segment()+
  # scale_color_manual(values=rev(wes_palette(n=3, name="BottleRocket2",type="discrete")))
  scale_colour_brewer(palette="Set1")



# which_dataset <- "2019-03-06_17-56-39"
# time_input <- "278"
# color_path <- "mean_angle"
# here("Image_analysis/R/plots", which_dataset,time_input,color_path)
# path <- here("Image_analysis/R/plots", which_dataset,time_input,color_path)
# dir.create(path,recursive = TRUE)
# selected_frame <- 2
# file.path(path,paste0("tp_",selected_tp,"_",round(selected_frame,3),".png"))
# 
# 
# plot_image_with_path("current_frame",4*2,conversion_factor,"minutes",18,"2019-03-06_17-56-39",0,50,30*2,10,"ID","with_image")
#   

```




##Plots1

```{r, echo=FALSE}



imported_data %>%
  select(hours, dataset_ID, TrackID) %>%
  group_by(hours, dataset_ID) %>%
  summarise(.,n = n_distinct(TrackID)) %>%
  ggplot(.,aes(x=hours,y=n,fill=dataset_ID,colour=dataset_ID))+
  #scale_colour_manual(values = wes_palette("BottleRocket2"))+
  #geom_line()+
  geom_smooth(method="loess")+
  ylab("Number of tracked worms")+
  theme_classic()

imported_data %>%
  select(hours,dataset_ID, TrackID, Duration_of_track) %>%
  group_by(hours, dataset_ID) %>%
  summarise(., mean_duration =mean(Duration_of_track)/downsampled_fps) %>%
  ggplot(.,aes(x=hours,y=mean_duration,fill=dataset_ID,colour=dataset_ID))+
  #scale_colour_manual(values = wes_palette("BottleRocket2"))+
  #geom_line()+
  geom_smooth(method="loess")+
  geom_hline(yintercept=duration,color="red")+
  ylab("Mean duration of tracks (seconds)")+
  theme_classic()


```


## Plot grouped images for standard parameters
```{r, echo=TRUE}

params <- grep("p\\_.+",colnames(dfp),value = TRUE)
dfp_for_plotting <- dfp %>%
  # filter(!dataset_ID %in% exps_out) %>%
  group_by(hours,dataset_ID,plate_type)%>%
  unite("experiment", c("dataset_ID","worm_type", "plate_type"), sep= " ") %>%
  group_by(experiment,hours,minutes,tp) %>%
  summarise_at(.vars = params,
               .funs = c(mean_per_minute="mean"))

params <- grep("p\\_.+",colnames(dfp_for_plotting),value = TRUE)
for (i in params){
print(ggplot(dfp_for_plotting, aes_string(x="hours",y=i))+
      #geom_ribbon(aes(ymin =  median_angle_per_minute - iqr_angle_per_minute, ymax = median_angle_per_minute + iqr_angle_per_minute))+
      geom_line(size=0.5)+
      ggtitle(i)+
      theme_classic()+
      # scale_x_continuous(breaks = seq(0, max(dfp_for_plotting$hours), 1))+
      facet_wrap(~experiment)
      #ggsave(paste0(i,".png"))
)
}

# 
# dfp$angle_mean_mmed <- mmed(dfp$mean_angle)
# 
# dfp2 <- dfp %>%
#   group_by(hours,dataset_ID,plate_type)%>%
#   unite("experiment", c("dataset_ID","worm_type", "plate_type"), sep= " ")%>%
#   group_by(experiment,hours,minutes)%>%
#   summarise(turns_mean_per_minute = mean(turns_per_minute), turns_mean_per_minute_ml=mean(turns_per_minute_ml), size_mean_per_minute=mean(mean_size),eccentricity_mean_per_minute=mean(mean_eccentricity),angle_mean_per_minute=mean(mean_angle),angle_mmed_mean_per_minute=mean(angle_mean_mmed),velocity_mean_per_minute=mean(mean_velocity), sd_velocity_mean_per_minute=mean(sd_velocity),displacement_mean_per_minute=mean(mean_displacement))
# 
# params <- c(params, "angle_mmed_mean_per_minute")
# for (i in params){
# print(ggplot(dfp2, aes_string(x="hours",y=i))+
#       #geom_ribbon(aes(ymin =  median_angle_per_minute - iqr_angle_per_minute, ymax = median_angle_per_minute + iqr_angle_per_minute))+
#       geom_line(size=0.5)+
#       ggtitle(i)+
#       theme_classic()+
#       scale_x_continuous(breaks = seq(0, max(dfp2$hours), 1))+
#       facet_wrap(~experiment)+
#       ggsave(paste0(i,".png"))
# )
# }

```

##Plot grouped images for standard parameters
```{r, echo=TRUE}

save_path <- file.path(target_folder_base,"analysis","191108")
save_path

chosen_exps_1 <- c(
                 #"2019-03-06_17-56-39",
                 #"2019-03-11_17-54-09",
                 # "2019-03-18_18-01-40",
                 #"2019-03-19_17-40-32"
                 "2019-03-26_19-27-16",
                 "2019-03-27_18-24-47")

chosen_exps_2 <-c("2019-05-07_12-15-40", #daf2 dauer
                  "2019-04-23_17-46-08")
                   

chosen_exps_3 <- c("2019-03-25_18-10-06") #no food


chosen_exps_4 <-c("2019-07-08_18-33-57", #1:5 OP50
                "2019-07-09_18-22-34") #1:5 OP50

chosen_exps_5 <-c("2019-04-30_14-15-44", #L2
                  "2019-05-04_15-36-42")


params <- grep("p\\_.+",colnames(dfp),value = TRUE)
sem <- function(x) sd(x)/sqrt(length(x))
i <- params[1]
for (i in params){
  dfp_for_plotting <<- dfp %>%
  filter(dataset_ID %in% chosen_exps_1 | dataset_ID %in% chosen_exps_2 | dataset_ID %in% chosen_exps_3 | dataset_ID %in% chosen_exps_4 | dataset_ID %in% chosen_exps_5) %>%
  mutate(annotation = ifelse(dataset_ID %in% chosen_exps_1, "N2 dauers 1:10",NA)) %>%
  mutate(annotation = ifelse(dataset_ID %in% chosen_exps_2, "daf2 dauers",annotation)) %>%
  mutate(annotation = ifelse(dataset_ID %in% chosen_exps_3, "N2 dauers no food",annotation)) %>%
  mutate(annotation = ifelse(dataset_ID %in% chosen_exps_4, "N2 dauers 1:5",annotation))%>%
  mutate(annotation = ifelse(dataset_ID %in% chosen_exps_5, "L2",annotation))%>%
  #round per half an hour
  mutate(hours_rounded= ceiling(hours* 2) / 2) %>%
  group_by(annotation, hours_rounded) %>%
  mutate(number_of_tracks_per_roundedtp_exptype = n()) %>%
  mutate(parameter_mean_per_minute = mean(!!sym(i)),
            parameter_sem_per_minute = sem(!!sym(i))) %>%
  group_by(annotation) %>%
  mutate(mean_number_of_tracks_per_roundedtp_exptype = mean(number_of_tracks_per_roundedtp_exptype)) %>%
  ungroup() %>%
  mutate(annotation = paste0(annotation, "\n(", round(mean_number_of_tracks_per_roundedtp_exptype),")"))

  
  print(ggplot(dfp_for_plotting,aes(x=hours_rounded,y=parameter_mean_per_minute,color=annotation,group=annotation,palette = "jco"))+
        geom_line(size=0.75)+
        geom_point()+
        #geom_errorbar(width=.1, aes(ymin=parameter_mean_per_minute-parameter_sd_per_minute, ymax=parameter_mean_per_minute+parameter_sd_per_minute))+
        geom_ribbon(aes(ymin=parameter_mean_per_minute-parameter_sem_per_minute, ymax=parameter_mean_per_minute+parameter_sem_per_minute), fill="white",linetype = 0, alpha=0.2)+
        ggtitle(paste0(i," with standard error of the mean"))+
        scale_x_continuous(limits = c(0,7),breaks = seq(0, 7, 1))+
        xlab("hours") + ylab(i)+
        theme_black()+
        scale_color_jco()+
        theme(legend.direction="vertical")+
        #theme(axis.title=element_blank(), axis.text=element_blank(), axis.ticks=element_blank(), plot.background = element_rect(fill = "black"))
        ggsave(file.path(save_path,paste0(i,"_grouped",".png")))
  )
}
```



```{r, echo=TRUE}

save_path <- file.path(target_folder_base,"analysis","191108")
save_path


for (i in params){

  dfp_for_plotting <<- dfp %>%
    filter(dataset_ID %in% chosen_exps_1 | dataset_ID %in% chosen_exps_2 | dataset_ID %in% chosen_exps_3 | dataset_ID %in% chosen_exps_4) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_1, "N2 dauers 1:10",NA)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_2, "daf2 dauers",annotation)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_3, "N2 dauers no food",annotation)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_4, "N2 dauers 1:5",annotation))%>%
    mutate(time_annotation = ifelse(hours >= 0 & hours <= 1, "1h",NA)) %>%
    mutate(time_annotation = ifelse(hours > 1 & hours <= 2, "2h",time_annotation)) %>%
    mutate(time_annotation = ifelse(hours > 2 & hours <= 3, "3h",time_annotation)) %>%
    mutate(time_annotation = ifelse(hours > 3 & hours <= 4, "4h",time_annotation)) %>%
    mutate(time_annotation = ifelse(hours > 4 & hours <= 5, "5h",time_annotation)) %>%
    mutate(time_annotation = ifelse(hours > 5 & hours <= 6, "6h",time_annotation)) %>%
    mutate(time_annotation = ifelse(hours > 6 & hours <= 7, "7h",time_annotation))%>%
    na.omit()

  

   print(
     ggplot(dfp_for_plotting,aes_string(x="time_annotation",y=i,fill="annotation"))+
    geom_boxplot(outlier.shape=1,outlier.color="white")+
    # geom_violin(outlier.shape=1,outlier.color="white")+
    #ggtitle(paste0(i," with standard error of the mean"))+
    #scale_x_continuous(limits = c(0,7))+
    xlab("hours") + ylab(i)+
    theme_black()+
    scale_fill_jco()+
    theme(legend.direction="vertical")  
   )
    ggsave(file.path(save_path,paste0(i,"_boxplot",".png")))
   
   mean_dfp_for_plotting <- dfp_for_plotting %>%
     group_by(time_annotation,annotation) %>%
      mutate(parameter_mean_per_hour = mean(!!sym(i)),
          parameter_sd_per_hour = sd(!!sym(i)))
  
   print(
     ggplot(mean_dfp_for_plotting, aes(x=time_annotation,y=parameter_mean_per_hour,fill=annotation)) +  
      geom_bar(stat="identity",position=position_dodge())+
      #geom_errorbar(aes(ymin=parameter_mean_per_hour-parameter_sd_per_hour, ymax=parameter_mean_per_hour+parameter_sd_per_hour), width=.2,position=position_dodge(.9),color="white")+
      xlab("hours") + ylab(i)+
      theme_black()+
      scale_fill_jco()+
      theme(legend.direction="vertical")  
   )
   ggsave(file.path(save_path,paste0(i,"_barplot",".png")))

  
   
} 
    
```


```{r, echo=TRUE}

dfp$hours_shuffled <- sample(dfp$hours, replace = FALSE)

for (i in params){
  dfp2 <- dfp %>%
  filter(dataset_ID %in% chosen_exps) %>%
  mutate(hours_rounded= ceiling(hours_shuffled* 2) / 2) %>%
  group_by(hours_rounded)%>%
  summarise(parameter_mean_per_minute = mean(!!sym(i)),
            parameter_sd_per_minute = sem(!!sym(i)))
  
  print(ggplot(dfp2,aes(x=hours_rounded,y=parameter_mean_per_minute))+
        geom_line(size=0.5,color="blue")+
        #geom_errorbar(width=.1, aes(ymin=parameter_mean_per_minute-parameter_sd_per_minute, ymax=parameter_mean_per_minute+parameter_sd_per_minute))+
        geom_ribbon(aes(ymin=parameter_mean_per_minute-parameter_sd_per_minute, ymax=parameter_mean_per_minute+parameter_sd_per_minute), alpha=0.3)+
        ggtitle(paste0(i," n=",length(chosen_exps)," with standard error of the mean"))+
        theme_classic()+
        scale_x_continuous(breaks = seq(0, max(dfp$hours), 1))+
        xlab("hours") + ylab(i)
        #ggsave(paste0(i,".png"))
  )
}       


```

## Cumulative distributions over time average over all datasets

```{r, echo=TRUE}

for (i in params){
  dfp2 <- dfp %>%
    filter(dataset_ID %in% chosen_exps_1 | dataset_ID %in% chosen_exps_2 | dataset_ID %in% chosen_exps_3 | dataset_ID %in% chosen_exps_4) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_1, "N2 dauers 1:10",NA)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_2, "daf2 dauers",annotation)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_3, "N2 dauers no food",annotation)) %>%
    mutate(annotation = ifelse(dataset_ID %in% chosen_exps_4, "N2 dauers 1:5",annotation))%>%
    mutate(hours_rounded= ceiling(hours* 2) / 2) %>%
    group_by(annotation) %>%
    mutate(N=paste0(annotation, " N= ",n_distinct(annotation), " datasets"))
  
  for(w in unique(dfp2$annotation)){
    dfp3 <- dfp2 %>%
      filter(annotation == w) %>%
      group_by(hours_rounded) %>%
      mutate(N_worms= n()) %>%
      ungroup() %>%
      mutate(sd_N_worms=sd(N_worms))%>%
      mutate(mean_N_worms=mean(N_worms))
  
    print(ggplot(dfp3,aes_string(x = i, y = "hours_rounded",group="hours_rounded",height="..density.."))+
      geom_density_ridges_gradient(aes(fill = ..x..), scale = 5, size = 0.3) +
      scale_fill_gradientn(colours = c("#0D0887FF", "#CC4678FF", "#F0F921FF"))+
      scale_x_continuous(limits = c(0, NA)) +
      theme_black()+
      theme(legend.position = "none")+
      ggtitle(paste0(gsub("p\\_(.+)","\\1",i)," ",w, " ", round(dfp3$mean_N_worms,0), "+-", round(dfp3$sd_N_worms,0)))+
      ggsave(file.path(save_path,paste0(i,"_", w,"_distribution",".png"))))
  }

}


```

## Plot gifs of parameters
```{r, echo=TRUE, out.width = '4%'}

for (i in params){
  dfp2 <- dfp %>%
  filter(dataset_ID %in% chosen_exps) %>%
  mutate(hours_rounded= ceiling(hours* 2) / 2) %>%
  group_by(hours_rounded)%>%
  summarise(parameter_mean_per_minute = mean(!!sym(i)),
            parameter_sd_per_minute = sem(!!sym(i)))
  
  print(ggplot(dfp2,aes(x=hours_rounded,y=parameter_mean_per_minute))+
        geom_line(size=0.5,color="blue")+
        #geom_errorbar(width=.1, aes(ymin=parameter_mean_per_minute-parameter_sd_per_minute, ymax=parameter_mean_per_minute+parameter_sd_per_minute))+
        geom_ribbon(aes(ymin=parameter_mean_per_minute-parameter_sd_per_minute, ymax=parameter_mean_per_minute+parameter_sd_per_minute), alpha=0.3)+
        ggtitle(paste0(i," n=",length(chosen_exps)," with standard error of the mean"))+
        theme_classic()+
        scale_x_continuous(breaks = seq(0, max(dfp$hours), 1))+
        xlab("hours") + ylab(i)
        #ggsave(paste0(i,".png"))
  )
}           
chosen_dataset <- "2019-01-23_16-07-02"
dfp2 <- dfp %>%
  group_by(minutes,dataset_ID,plate_type,tp)%>%
  filter(mean_displacement > 100)%>%
  summarise(size_median_per_minute=median(mean_size),eccentricity_median_per_minute=median(mean_eccentricity),angle_median_per_minute=median(mean_angle),velocity_median_per_minute=median(mean_velocity), sd_velocity_median_per_minute=median(sd_velocity),displacement_median_per_minute=median(mean_displacement))%>%
  filter(dataset_ID == chosen_dataset)

for (i in dfp2$tp){
  
dfp3 <- dfp2 %>%
    filter(tp <= i)
  
  p1 <- ggplot(dfp3,aes_string(x="minutes",y="angle_median_per_minute"))+
      geom_line(size=1,color="white")+
      scale_x_continuous(limits=c(0, max(dfp2$minutes)))+
      scale_y_continuous(limits=c(0, max(dfp2$angle_median_per_minute)))+
      xlab("")+
      ylab("median\nangle")+
      theme_black()+
      theme(axis.title.x = element_text(size = rel(1.5)),
            axis.title.y = element_text(size = rel(1.5)))       
  
#plot_image_with_path(offset,selected_minute,which_dataset,max_number_gaps,duration,which_frame,color_path,with_image) 
  p2 <- plot_image_with_path(5,"tp",i,chosen_dataset,5,100,1,"mean_angle","no")+theme_black()+xlab("")+ylab("")+
      theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        legend.key.height=unit(0.5,"line"))


  p3 <- ggplot(dfp3,aes_string(x="minutes",y="velocity_median_per_minute"))+
      geom_line(size=1,color="white")+
      scale_x_continuous(limits=c(0, max(dfp2$minutes)))+
      scale_y_continuous(limits=c(0, max(dfp2$velocity_median_per_minute)))+
      xlab("")+
      ylab("median\nvelocity")+
      theme_black()+
      theme(axis.title.x = element_text(size = rel(1.5)),
            axis.title.y = element_text(size = rel(1.5)))  

  p4 <- plot_image_with_path(5,"tp",i,chosen_dataset,5,100,1,"velocity","no")+theme_black()+xlab("")+ylab("")+
      theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        legend.key.height=unit(0.5,"line"))

  
  p5 <- ggplot(dfp3,aes_string(x="minutes",y="displacement_median_per_minute"))+
      geom_line(size=1,color="white")+
      scale_x_continuous(limits=c(0, max(dfp2$minutes)))+
      scale_y_continuous(limits=c(0, max(dfp2$displacement_median_per_minute)))+
      xlab("minutes")+
      ylab("median\ndisplacement")+
      theme_black()+
      theme(axis.title.x = element_text(size = rel(1.5)),
            axis.title.y = element_text(size = rel(1.5)))  
  
  p6 <- plot_image_with_path(5,"tp",i,chosen_dataset,5,100,1,"displacement","no")+theme_black()+xlab("")+ylab("")+
      theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank(),
        legend.key.height=unit(0.5,"line"))

  
 p_all <- plot_grid(p1, p2, p3,p4,p5,p6,
          ncol = 2, nrow = 3,
          rel_widths = c(1,1))

 p_all
 save_plot(paste0("plots/",chosen_dataset,"_",round(i,3),".png"), p_all, base_height=10,base_aspect_ratio = 1.1)
 print(paste0("Saved plot Nr.",round(i,3)))
 
}


```


```{r, echo=TRUE}
###check if this function is up to date
#plot_image_with_path_centered(which_tracks,offset,conversion_factor,time_input_type,time_input,which_dataset,max_number_gaps,duration,selected_frame,color_path,image)
plot_image_with_path_centered("all_frames",secs_angle_offset*downsampled_fps,conversion_factor,"minutes",129,"2019-03-06_17-56-39",max_gaps,secs_min_tracked*downsampled_fps,10, "mean_angle","no_image")

minutes <- dfp %>%
  filter(dataset_ID == "2019-03-06_17-56-39")

minutes_unique <- unique(minutes$minutes)
minutes_unique
minutes_length <- length(minutes_unique)
minutes_length
```


```{r, echo=TRUE}

for (i in (minutes_unique)){
  plot_image_with_path_centered("all_frames",secs_angle_offset*downsampled_fps,conversion_factor,"minutes",i,"2019-03-06_17-56-39",max_gaps,secs_min_tracked*downsampled_fps,10, "mean_angle","no_image")
  save_plot(paste0("plots/","centered_",sprintf("%03d", i),".png"),pc,base_height=10,base_aspect_ratio = 1.1)
  print(paste0("Saved plot for minute ",sprintf("%03d", i)))
}

```



```{r, echo=TRUE}
dfp2 <- dfp %>%
  group_by(minutes,dataset_ID,plate_type)%>%
  unite("experiment", c("dataset_ID","plate_type"), sep= " ")

ggplot(dfp2,aes(x = mean_angle, y = mean_velocity))+
  stat_density2d(geom="raster", aes(fill = ..density..),contour = FALSE)+
  scale_fill_viridis(option = "inferno")+
  scale_x_reverse(limits=c(180,0), breaks = seq(180, 0, by = -36))+
  scale_y_continuous(limits=c(0,15), breaks = seq(0,15, by = 5))+
  theme_classic2()+
  ggtitle("2D density velocity against angle velocity")+
  facet_wrap(~experiment)

```


```{r, echo=TRUE}
test <- MASS::geyser

data <- data.frame(dfp2$mean_angle,dfp2$mean_velocity)
colnames(data) <- c("mean_angle","mean_velocity")
data
kd <- with(data, MASS::kde2d(mean_angle,mean_velocity, n = 50))
p <- plot_ly(x = kd$x, y = kd$y, z = kd$z) %>% add_surface()
p
chart_link = api_create(p, filename="surface-2")
chart_link

```


