---
title: "headseq_analysis_deseq2_dotplot"
author: "Friedrich Preußer"
date: "7/26/2021"
output: html_document
---

```{r, results='hide',message='false', warning='false'}
# for all good stuff
library(tidyverse)
# for file manipulation
library(here)
#for colors
library(viridis)
#for venn diagram
library(ggvenn)
#for converting gene IDs and goterm analysis
library(gprofiler2)


```



# import data
```{r echo=TRUE, message=FALSE, warning=FALSE}


location_files_to_load <- "/Users/fpreuss/Documents/PhD/Data/headseq/csvs/"

data <- list.files(location_files_to_load,pattern=".*diff_A.*",full.names = TRUE) %>%
  map_df(function(x) read.table(x,sep=",",header=TRUE) %>% mutate(file=basename(x))) %>%
  mutate(compared_tps = gsub("diff_A_(.h)_vs_B_(.h).*","\\1",file)) %>%
  filter(compared_tps %in% c("3h","6h","9h"))

expressed_genes_head <- read_csv("/Users/fpreuss/Documents/PhD/Data/headseq/expressed_genes_head_all_exps.txt") %>%
  pull()

```


# take differentially expressed genes as calculated above (those that are exclusively differentially expressed in one condition)
```{r,results='hide',message='false',warning='false'}



go_analysis <- function(tp,data){
  
  data_filtered <- data %>%
    filter(compared_tps %in% tp)
  
    #get the list of differentially expressed genes of interest
    genesOfInterest <- data_filtered$gene_wb
  
  
    #calculate enriched GO terms
    #against all annotated genes
    # goResults <- gost(query = genesOfInterest,
    #                 organism = 'celegans',
    #                 evcodes = TRUE)

    
    #with custom background
    goResults <- gost(query = genesOfInterest,
                    organism = 'celegans',
                    evcodes = TRUE,
                    domain_scope="custom",
                    user_threshold = 0.01,
                    custom_bg = expressed_genes_head)
    
    
    # transform to data frame
    go_results <- goResults$result
    #sort by pvalue
    go_results <- go_results[order(go_results$p_value),] %>%
      #add tp to know which differnetially expressed genes were used here
      mutate(tp = tp)
    return(go_results)
    
}


tps <- unique(data$compared_tps)

go_results_all <- tps %>%
  map_df(function(x) go_analysis(x,data)) %>%
  #filter out transfac missannotation
  filter(!term_name == "Transfac") %>%
  mutate(parents=as.character(parents))

write.csv(go_results_all,file=file.path(here(),"enriched_go_terms.txt"),row.names = FALSE)

#only top 3 terms for each tp
#3h
go_results_all_filtered_three <- go_results_all %>%
  filter(tp == "3h") %>%
  top_n(-3,p_value)

#6h
go_results_all_filtered_six <- go_results_all %>%
  filter(tp == "6h") %>%
  top_n(-3,p_value)

#9h, here we select 4 since one appears twice
go_results_all_filtered_nine <- go_results_all %>%
  filter(tp == "9h") %>%
  top_n(-4,p_value) %>%
  distinct(term_name, .keep_all= TRUE)

go_results_all_filtered <- rbind(go_results_all_filtered_three,
                             go_results_all_filtered_six,
                             go_results_all_filtered_nine)

#gene ratio ( genes related to GO term / total number of sig genes)) == precision
# precision is defined as:
#the proportion of genes in the input list that are annotated to the function
# --> the number of genes in the input query that are annotated to the corresponding term /
#     number of genes that were included in the query
ggplot(data = go_results_all_filtered, aes(x = tp, y = term_name, 
                        color = `p_value`, size = precision)) + 
  geom_point() +
  scale_radius(range=c(5, 15))+
  scale_color_viridis(option = "mako") +
  theme_bw() + 
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis")+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.65,hjust=0.75))

ggsave(file.path(here(), paste0("A_vs_B_go_enrichment_doplot_over_all_tps",".png")))


```


